import { redirect } from "next/navigation";
import { getDashboardContext } from "@/lib/dashboard";
import { createPushMessage } from "./actions";

type Params=Promise<{saved?:string;error?:string}>;
export default async function PushPage({searchParams}:{searchParams:Params}) {
  const params=await searchParams; const context=await getDashboardContext();
  if(!context.user)redirect("/login?next=/dashboard/push"); if(!context.organizationId)redirect("/dashboard/onboarding");
  const {data}=await context.supabase.from("push_messages").select("id,title,body,target_type,segment_name,moderation_status,delivery_status,rejection_reason,sent_count,submitted_at,sent_at").eq("business_id",context.organizationId).order("submitted_at",{ascending:false}).limit(100);
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_right,#312e81_0%,#082032_34%,#020617_100%)] px-5 py-16 text-white sm:px-8"><section className="mx-auto max-w-5xl"><span className="rounded-full bg-indigo-300/15 px-4 py-2 text-sm font-black text-indigo-100">🔔 Kunden-App Push</span><h1 className="mt-5 text-5xl font-black">Push-Nachrichten</h1><p className="mt-3 text-slate-300">Nachrichten werden erst nach Freigabe durch Admin oder Global Admin versendet.</p>
  {params.saved?<p className="mt-6 rounded-2xl bg-amber-300/10 p-4 text-amber-100">Push-Nachricht wurde zur Freigabe eingereicht.</p>:null}{params.error?<p className="mt-6 rounded-2xl bg-red-300/10 p-4 text-red-100">Speichern nicht möglich ({params.error}).</p>:null}
  <form action={createPushMessage} className="mt-8 grid gap-4 rounded-3xl border border-white/10 bg-white/[0.06] p-6"><label className="grid gap-2 font-bold">Titel<input name="title" required maxLength={50} className="rounded-xl bg-slate-900 p-3"/></label><label className="grid gap-2 font-bold">Nachricht<textarea name="body" required maxLength={150} rows={4} className="rounded-xl bg-slate-900 p-3"/></label><label className="grid gap-2 font-bold">Zielgruppe<select name="target_type" className="rounded-xl bg-slate-900 p-3"><option value="all">Alle Kunden</option><option value="segment">Segment (Platinum)</option></select></label><label className="grid gap-2 font-bold">Segment<input name="segment_name" maxLength={100} placeholder="z. B. inaktive Kunden" className="rounded-xl bg-slate-900 p-3"/></label><button className="rounded-xl bg-indigo-300 px-5 py-3 font-black text-slate-950">Zur Freigabe einreichen</button></form>
  <h2 className="mt-12 text-3xl font-black">Verlauf</h2><div className="mt-5 grid gap-4">{(data??[]).map(message=><article key={message.id} className="rounded-3xl border border-white/10 bg-white/[0.06] p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-xl font-black">{message.title}</h3><p className="mt-2 text-slate-300">{message.body}</p></div><Status value={message.moderation_status}/></div><p className="mt-3 text-sm text-slate-500">{message.target_type}{message.segment_name?` · ${message.segment_name}`:""} · Versand: {message.delivery_status} · {message.sent_count} Empfänger</p>{message.rejection_reason?<p className="mt-3 font-bold text-red-200">Begründung: {message.rejection_reason}</p>:null}</article>)}{!data?.length?<p className="rounded-3xl border border-white/10 p-7 text-slate-400">Noch keine Push-Nachrichten.</p>:null}</div>
  </section></main>;
}
function Status({value}:{value:string}){const label=value==="approved"?"Freigegeben":value==="rejected"?"Abgelehnt":"Wartet auf Freigabe";const tone=value==="approved"?"text-emerald-100 bg-emerald-300/15":value==="rejected"?"text-red-100 bg-red-300/15":"text-amber-100 bg-amber-300/15";return <span className={`h-fit rounded-full px-3 py-2 text-xs font-black ${tone}`}>{label}</span>}
