import type { Locale } from "./config";

export type AuthMessages = {
  metaTitle: string; metaDescription: string;
  back: string; title: string; intro: string;
  tabs: { signin: string; signup: string; magic: string };
  nickname: string; nicknamePlaceholder: string; email: string; password: string; passwordPlaceholder: string;
  consentBefore: string; privacy: string; consentAnd: string; terms: string; consentAfter: string;
  waiting: string; sendLink: string; createAccount: string; signIn: string;
  magicSent: string; accountCreated: string; unavailable: string;
};

export const authMessages: Record<Locale, AuthMessages> = {
  de: { metaTitle: "Geschäftskonto anmelden", metaDescription: "Beim TapRadar Geschäftsdashboard anmelden oder ein neues Geschäftskonto erstellen.", back: "Zurück zur Website", title: "Anmelden", intro: "Melde dich mit E-Mail und Passwort an. Für Tests kannst du auch ein neues Konto erstellen.", tabs: { signin: "Login", signup: "Neu", magic: "Link" }, nickname: "Anzeigename", nicknamePlaceholder: "Mein Geschäft", email: "E-Mail", password: "Passwort", passwordPlaceholder: "Mindestens 6 Zeichen", consentBefore: "Ich akzeptiere die", privacy: "Datenschutzerklärung", consentAnd: "und die", terms: "AGB", consentAfter: ".", waiting: "Bitte warten...", sendLink: "Login-Link senden", createAccount: "Konto erstellen", signIn: "Anmelden", magicSent: "Login-Link wurde gesendet. Bitte prüfe dein E-Mail-Postfach.", accountCreated: "Konto wurde erstellt. Falls Supabase eine Bestätigung verlangt, prüfe bitte dein E-Mail-Postfach.", unavailable: "Supabase ist noch nicht verbunden. Bitte trage zuerst die Umgebungsvariablen ein." },
  en: { metaTitle: "Business account login", metaDescription: "Sign in to the TapRadar business dashboard or create a new business account.", back: "Back to website", title: "Log in", intro: "Sign in with your email and password. You can also create a new account for testing.", tabs: { signin: "Log in", signup: "New", magic: "Link" }, nickname: "Display name", nicknamePlaceholder: "My business", email: "Email", password: "Password", passwordPlaceholder: "At least 6 characters", consentBefore: "I accept the", privacy: "Privacy Policy", consentAnd: "and the", terms: "Terms", consentAfter: ".", waiting: "Please wait...", sendLink: "Send login link", createAccount: "Create account", signIn: "Log in", magicSent: "The login link has been sent. Please check your inbox.", accountCreated: "Your account has been created. If Supabase requires confirmation, please check your inbox.", unavailable: "Supabase is not connected yet. Please configure the environment variables first." },
  tr: { metaTitle: "İşletme hesabı girişi", metaDescription: "TapRadar işletme paneline giriş yapın veya yeni bir işletme hesabı oluşturun.", back: "Web sitesine dön", title: "Giriş yap", intro: "E-posta ve şifrenizle giriş yapın. Test için yeni bir hesap da oluşturabilirsiniz.", tabs: { signin: "Giriş", signup: "Yeni", magic: "Bağlantı" }, nickname: "Görünen ad", nicknamePlaceholder: "İşletmem", email: "E-posta", password: "Şifre", passwordPlaceholder: "En az 6 karakter", consentBefore: "Şunları kabul ediyorum:", privacy: "Gizlilik Politikası", consentAnd: "ve", terms: "Koşullar", consentAfter: ".", waiting: "Lütfen bekleyin...", sendLink: "Giriş bağlantısı gönder", createAccount: "Hesap oluştur", signIn: "Giriş yap", magicSent: "Giriş bağlantısı gönderildi. Lütfen e-posta kutunuzu kontrol edin.", accountCreated: "Hesabınız oluşturuldu. Supabase onay isterse e-posta kutunuzu kontrol edin.", unavailable: "Supabase henüz bağlı değil. Lütfen önce ortam değişkenlerini yapılandırın." },
  "sr-Latn": { metaTitle: "Prijava poslovnog naloga", metaDescription: "Prijavite se na TapRadar poslovnu kontrolnu tablu ili napravite novi poslovni nalog.", back: "Nazad na veb-sajt", title: "Prijava", intro: "Prijavite se putem e-pošte i lozinke. Za testiranje možete napraviti i novi nalog.", tabs: { signin: "Prijava", signup: "Novi", magic: "Link" }, nickname: "Prikazano ime", nicknamePlaceholder: "Moje preduzeće", email: "E-pošta", password: "Lozinka", passwordPlaceholder: "Najmanje 6 znakova", consentBefore: "Prihvatam", privacy: "Politiku privatnosti", consentAnd: "i", terms: "Uslove", consentAfter: ".", waiting: "Sačekajte...", sendLink: "Pošalji link za prijavu", createAccount: "Napravi nalog", signIn: "Prijava", magicSent: "Link za prijavu je poslat. Proverite prijemno sanduče.", accountCreated: "Nalog je napravljen. Ako Supabase zahteva potvrdu, proverite prijemno sanduče.", unavailable: "Supabase još nije povezan. Prvo podesite promenljive okruženja." },
  bs: { metaTitle: "Prijava poslovnog računa", metaDescription: "Prijavite se na TapRadar poslovnu kontrolnu ploču ili kreirajte novi poslovni račun.", back: "Nazad na web stranicu", title: "Prijava", intro: "Prijavite se e-poštom i lozinkom. Za testiranje možete kreirati i novi račun.", tabs: { signin: "Prijava", signup: "Novi", magic: "Link" }, nickname: "Prikazano ime", nicknamePlaceholder: "Moja firma", email: "E-pošta", password: "Lozinka", passwordPlaceholder: "Najmanje 6 znakova", consentBefore: "Prihvatam", privacy: "Politiku privatnosti", consentAnd: "i", terms: "Uslove", consentAfter: ".", waiting: "Molimo sačekajte...", sendLink: "Pošalji link za prijavu", createAccount: "Kreiraj račun", signIn: "Prijava", magicSent: "Link za prijavu je poslan. Provjerite prijemno sanduče.", accountCreated: "Račun je kreiran. Ako Supabase zahtijeva potvrdu, provjerite prijemno sanduče.", unavailable: "Supabase još nije povezan. Prvo podesite varijable okruženja." },
  hr: { metaTitle: "Prijava poslovnog računa", metaDescription: "Prijavite se na poslovnu nadzornu ploču TapRadar ili izradite novi poslovni račun.", back: "Natrag na web-stranicu", title: "Prijava", intro: "Prijavite se e-poštom i lozinkom. Za testiranje možete izraditi i novi račun.", tabs: { signin: "Prijava", signup: "Novi", magic: "Poveznica" }, nickname: "Prikazano ime", nicknamePlaceholder: "Moja tvrtka", email: "E-pošta", password: "Lozinka", passwordPlaceholder: "Najmanje 6 znakova", consentBefore: "Prihvaćam", privacy: "Pravila privatnosti", consentAnd: "i", terms: "Uvjete", consentAfter: ".", waiting: "Pričekajte...", sendLink: "Pošalji poveznicu za prijavu", createAccount: "Izradi račun", signIn: "Prijava", magicSent: "Poveznica za prijavu je poslana. Provjerite ulaznu poštu.", accountCreated: "Račun je izrađen. Ako Supabase traži potvrdu, provjerite ulaznu poštu.", unavailable: "Supabase još nije povezan. Najprije postavite varijable okruženja." },
  hu: { metaTitle: "Üzleti fiók bejelentkezés", metaDescription: "Jelentkezzen be a TapRadar üzleti vezérlőpultjára, vagy hozzon létre új üzleti fiókot.", back: "Vissza a weboldalra", title: "Bejelentkezés", intro: "Jelentkezzen be e-mail-címmel és jelszóval. Teszteléshez új fiókot is létrehozhat.", tabs: { signin: "Belépés", signup: "Új", magic: "Hivatkozás" }, nickname: "Megjelenő név", nicknamePlaceholder: "Vállalkozásom", email: "E-mail", password: "Jelszó", passwordPlaceholder: "Legalább 6 karakter", consentBefore: "Elfogadom az", privacy: "Adatvédelmi tájékoztatót", consentAnd: "és a", terms: "Feltételeket", consentAfter: ".", waiting: "Kérjük, várjon...", sendLink: "Belépési hivatkozás küldése", createAccount: "Fiók létrehozása", signIn: "Bejelentkezés", magicSent: "A belépési hivatkozást elküldtük. Ellenőrizze a beérkező leveleit.", accountCreated: "A fiók létrejött. Ha a Supabase megerősítést kér, ellenőrizze a beérkező leveleit.", unavailable: "A Supabase még nincs csatlakoztatva. Először állítsa be a környezeti változókat." },
  ro: { metaTitle: "Autentificare cont de afaceri", metaDescription: "Autentificați-vă în panoul TapRadar sau creați un cont nou de afaceri.", back: "Înapoi la site", title: "Autentificare", intro: "Autentificați-vă cu adresa de e-mail și parola. Pentru testare puteți crea și un cont nou.", tabs: { signin: "Autentificare", signup: "Nou", magic: "Link" }, nickname: "Nume afișat", nicknamePlaceholder: "Afacerea mea", email: "E-mail", password: "Parolă", passwordPlaceholder: "Cel puțin 6 caractere", consentBefore: "Accept", privacy: "Politica de confidențialitate", consentAnd: "și", terms: "Termenii", consentAfter: ".", waiting: "Vă rugăm să așteptați...", sendLink: "Trimite linkul de autentificare", createAccount: "Creează cont", signIn: "Autentificare", magicSent: "Linkul de autentificare a fost trimis. Verificați căsuța de e-mail.", accountCreated: "Contul a fost creat. Dacă Supabase solicită confirmare, verificați căsuța de e-mail.", unavailable: "Supabase nu este încă conectat. Configurați mai întâi variabilele de mediu." },
  pl: { metaTitle: "Logowanie do konta firmowego", metaDescription: "Zaloguj się do panelu TapRadar lub utwórz nowe konto firmowe.", back: "Powrót do strony", title: "Logowanie", intro: "Zaloguj się za pomocą adresu e-mail i hasła. Do testów możesz też utworzyć nowe konto.", tabs: { signin: "Logowanie", signup: "Nowe", magic: "Link" }, nickname: "Nazwa wyświetlana", nicknamePlaceholder: "Moja firma", email: "E-mail", password: "Hasło", passwordPlaceholder: "Co najmniej 6 znaków", consentBefore: "Akceptuję", privacy: "Politykę prywatności", consentAnd: "oraz", terms: "Regulamin", consentAfter: ".", waiting: "Proszę czekać...", sendLink: "Wyślij link logowania", createAccount: "Utwórz konto", signIn: "Zaloguj się", magicSent: "Link logowania został wysłany. Sprawdź skrzynkę odbiorczą.", accountCreated: "Konto zostało utworzone. Jeśli Supabase wymaga potwierdzenia, sprawdź skrzynkę odbiorczą.", unavailable: "Supabase nie jest jeszcze połączony. Najpierw skonfiguruj zmienne środowiskowe." },
  bg: { metaTitle: "Вход в бизнес акаунт", metaDescription: "Влезте в бизнес таблото на TapRadar или създайте нов бизнес акаунт.", back: "Назад към сайта", title: "Вход", intro: "Влезте с имейл и парола. За тестове можете да създадете и нов акаунт.", tabs: { signin: "Вход", signup: "Нов", magic: "Линк" }, nickname: "Показвано име", nicknamePlaceholder: "Моят бизнес", email: "Имейл", password: "Парола", passwordPlaceholder: "Поне 6 знака", consentBefore: "Приемам", privacy: "Политиката за поверителност", consentAnd: "и", terms: "Условията", consentAfter: ".", waiting: "Моля, изчакайте...", sendLink: "Изпрати линк за вход", createAccount: "Създай акаунт", signIn: "Вход", magicSent: "Линкът за вход е изпратен. Проверете входящата си поща.", accountCreated: "Акаунтът е създаден. Ако Supabase изисква потвърждение, проверете входящата си поща.", unavailable: "Supabase все още не е свързан. Първо настройте променливите на средата." },
};

