import type { Locale } from "./config";

export type AuthMessages = {
  metaTitle: string;
  metaDescription: string;
  back: string;
  title: string;
  intro: string;
  tabs: { signin: string; signup: string; magic: string };
  email: string;
  password: string;
  passwordPlaceholder: string;
  show: string;
  hide: string;
  remember: string;
  forgot: string;
  consentBefore: string;
  privacy: string;
  consentAnd: string;
  terms: string;
  consentAfter: string;
  waiting: string;
  sendLink: string;
  createAccount: string;
  signIn: string;
  magicSent: string;
  accountCreated: string;
  unavailable: string;
  passwordUpdated: string;
  legalRequired: string;
  signInFailed: string;
  signupFailed: string;
  magicFailed: string;
  businessTitle: string;
  businessIntro: string;
};

export const authMessages: Record<Locale, AuthMessages> = {
  de: { metaTitle: "Bei TapRadar anmelden", metaDescription: "Alle Stempelkarten und Belohnungen in einer App.", back: "Zurück zur Website", title: "Anmelden", intro: "Melde dich sicher mit deiner E-Mail-Adresse und deinem Passwort an.", tabs: { signin: "Login", signup: "Neu", magic: "Link" }, email: "E-Mail", password: "Passwort", passwordPlaceholder: "Mindestens 8 Zeichen", show: "Anzeigen", hide: "Ausblenden", remember: "Angemeldet bleiben", forgot: "Passwort vergessen?", consentBefore: "Ich akzeptiere die", privacy: "Datenschutzerklärung", consentAnd: "und die", terms: "AGB", consentAfter: ".", waiting: "Bitte warten...", sendLink: "Login-Link senden", createAccount: "Registrieren", signIn: "Anmelden", magicSent: "Login-Link wurde gesendet. Bitte prüfe dein E-Mail-Postfach.", accountCreated: "Konto wurde erstellt. Falls eine Bestätigung erforderlich ist, prüfe bitte dein E-Mail-Postfach.", unavailable: "Die Anmeldung ist momentan nicht verfügbar. Bitte versuche es später erneut.", passwordUpdated: "Dein Passwort wurde geändert. Du kannst dich jetzt anmelden.", legalRequired: "Bitte bestätige die AGB und die Kenntnisnahme der Datenschutzerklärung.", signInFailed: "Anmeldung nicht möglich. E-Mail oder Passwort ist falsch.", signupFailed: "Konto konnte nicht erstellt werden. Prüfe die Eingaben oder versuche es später erneut.", magicFailed: "Login-Link konnte nicht gesendet werden. Prüfe die Eingabe oder versuche es später erneut.", businessTitle: "Geschäftskonto erstellen", businessIntro: "Registriere dein Händlerkonto und richte anschließend Unternehmen und Filiale ein." },
  en: { metaTitle: "Sign in to TapRadar", metaDescription: "All loyalty cards and rewards in one app.", back: "Back to website", title: "Log in", intro: "Sign in securely with your email address and password.", tabs: { signin: "Log in", signup: "New", magic: "Link" }, email: "Email", password: "Password", passwordPlaceholder: "At least 8 characters", show: "Show", hide: "Hide", remember: "Keep me signed in", forgot: "Forgot password?", consentBefore: "I accept the", privacy: "Privacy Policy", consentAnd: "and the", terms: "Terms", consentAfter: ".", waiting: "Please wait...", sendLink: "Send login link", createAccount: "Create account", signIn: "Log in", magicSent: "The login link has been sent. Please check your inbox.", accountCreated: "Your account has been created. If confirmation is required, please check your inbox.", unavailable: "Login is currently unavailable. Please try again later.", passwordUpdated: "Your password has been changed. You can now log in.", legalRequired: "Please accept the Terms and acknowledge the Privacy Policy.", signInFailed: "Login failed. The email or password is incorrect.", signupFailed: "The account could not be created. Check your details or try again later.", magicFailed: "The login link could not be sent. Check your entry or try again later.", businessTitle: "Create business account", businessIntro: "Register your merchant account, then set up your business and location." },
  tr: { metaTitle: "TapRadar'a giriş yap", metaDescription: "Tüm damga kartları ve ödüller tek uygulamada.", back: "Web sitesine dön", title: "Giriş yap", intro: "E-posta adresin ve şifrenle güvenli şekilde giriş yap.", tabs: { signin: "Giriş", signup: "Yeni", magic: "Bağlantı" }, email: "E-posta", password: "Şifre", passwordPlaceholder: "En az 8 karakter", show: "Göster", hide: "Gizle", remember: "Oturumu açık tut", forgot: "Şifreni mi unuttun?", consentBefore: "Şunları kabul ediyorum:", privacy: "Gizlilik Politikası", consentAnd: "ve", terms: "Koşullar", consentAfter: ".", waiting: "Lütfen bekleyin...", sendLink: "Giriş bağlantısı gönder", createAccount: "Hesap oluştur", signIn: "Giriş yap", magicSent: "Giriş bağlantısı gönderildi. Lütfen e-posta kutunu kontrol et.", accountCreated: "Hesabın oluşturuldu. Onay gerekiyorsa e-posta kutunu kontrol et.", unavailable: "Giriş şu anda kullanılamıyor. Lütfen daha sonra tekrar dene.", passwordUpdated: "Şifren değiştirildi. Şimdi giriş yapabilirsin.", legalRequired: "Lütfen Koşulları ve Gizlilik Politikasını onayla.", signInFailed: "Giriş başarısız. E-posta veya şifre yanlış.", signupFailed: "Hesap oluşturulamadı. Bilgilerini kontrol et veya daha sonra tekrar dene.", magicFailed: "Giriş bağlantısı gönderilemedi. Bilgiyi kontrol et veya daha sonra tekrar dene.", businessTitle: "İşletme hesabı oluştur", businessIntro: "Satıcı hesabını oluştur, ardından işletmeni ve şubeni ayarla." },
  fr: { metaTitle: "Se connecter à TapRadar", metaDescription: "Toutes vos cartes de fidélité et récompenses dans une app.", back: "Retour au site", title: "Se connecter", intro: "Connectez-vous en toute sécurité avec votre adresse e-mail et votre mot de passe.", tabs: { signin: "Connexion", signup: "Nouveau", magic: "Lien" }, email: "E-mail", password: "Mot de passe", passwordPlaceholder: "Au moins 8 caractères", show: "Afficher", hide: "Masquer", remember: "Rester connecté", forgot: "Mot de passe oublié ?", consentBefore: "J'accepte la", privacy: "Politique de confidentialité", consentAnd: "et les", terms: "Conditions", consentAfter: ".", waiting: "Veuillez patienter...", sendLink: "Envoyer le lien", createAccount: "Créer un compte", signIn: "Se connecter", magicSent: "Le lien de connexion a été envoyé. Vérifiez votre boîte de réception.", accountCreated: "Votre compte a été créé. Si une confirmation est requise, vérifiez votre boîte de réception.", unavailable: "La connexion est momentanément indisponible. Réessayez plus tard.", passwordUpdated: "Votre mot de passe a été modifié. Vous pouvez maintenant vous connecter.", legalRequired: "Veuillez accepter les Conditions et la Politique de confidentialité.", signInFailed: "Connexion impossible. L'e-mail ou le mot de passe est incorrect.", signupFailed: "Le compte n'a pas pu être créé. Vérifiez vos informations ou réessayez plus tard.", magicFailed: "Le lien n'a pas pu être envoyé. Vérifiez votre saisie ou réessayez plus tard.", businessTitle: "Créer un compte professionnel", businessIntro: "Créez votre compte marchand, puis configurez votre entreprise et votre établissement." },
  it: { metaTitle: "Accedi a TapRadar", metaDescription: "Tutte le carte fedeltà e i premi in un'unica app.", back: "Torna al sito", title: "Accedi", intro: "Accedi in modo sicuro con e-mail e password.", tabs: { signin: "Accedi", signup: "Nuovo", magic: "Link" }, email: "E-mail", password: "Password", passwordPlaceholder: "Almeno 8 caratteri", show: "Mostra", hide: "Nascondi", remember: "Resta connesso", forgot: "Password dimenticata?", consentBefore: "Accetto l'", privacy: "Informativa sulla privacy", consentAnd: "e i", terms: "Termini", consentAfter: ".", waiting: "Attendi...", sendLink: "Invia link di accesso", createAccount: "Crea account", signIn: "Accedi", magicSent: "Il link di accesso è stato inviato. Controlla la posta.", accountCreated: "Il tuo account è stato creato. Se serve una conferma, controlla la posta.", unavailable: "L'accesso non è al momento disponibile. Riprova più tardi.", passwordUpdated: "La password è stata modificata. Ora puoi accedere.", legalRequired: "Accetta i Termini e l'Informativa sulla privacy.", signInFailed: "Accesso non riuscito. E-mail o password errati.", signupFailed: "Impossibile creare l'account. Controlla i dati o riprova più tardi.", magicFailed: "Impossibile inviare il link. Controlla i dati o riprova più tardi.", businessTitle: "Crea account aziendale", businessIntro: "Registra il tuo account commerciante, quindi configura azienda e sede." },
  es: { metaTitle: "Inicia sesión en TapRadar", metaDescription: "Todas tus tarjetas de fidelidad y recompensas en una app.", back: "Volver al sitio", title: "Iniciar sesión", intro: "Inicia sesión de forma segura con tu correo y contraseña.", tabs: { signin: "Acceso", signup: "Nuevo", magic: "Enlace" }, email: "Correo electrónico", password: "Contraseña", passwordPlaceholder: "Al menos 8 caracteres", show: "Mostrar", hide: "Ocultar", remember: "Mantener la sesión", forgot: "¿Olvidaste la contraseña?", consentBefore: "Acepto la", privacy: "Política de privacidad", consentAnd: "y los", terms: "Términos", consentAfter: ".", waiting: "Espera...", sendLink: "Enviar enlace", createAccount: "Crear cuenta", signIn: "Iniciar sesión", magicSent: "El enlace se ha enviado. Revisa tu correo.", accountCreated: "Tu cuenta se ha creado. Si se requiere confirmación, revisa tu correo.", unavailable: "El acceso no está disponible en este momento. Inténtalo más tarde.", passwordUpdated: "Tu contraseña ha cambiado. Ya puedes iniciar sesión.", legalRequired: "Acepta los Términos y la Política de privacidad.", signInFailed: "No se pudo iniciar sesión. El correo o la contraseña son incorrectos.", signupFailed: "No se pudo crear la cuenta. Revisa los datos o inténtalo más tarde.", magicFailed: "No se pudo enviar el enlace. Revisa los datos o inténtalo más tarde.", businessTitle: "Crear cuenta de empresa", businessIntro: "Registra tu cuenta de comercio y después configura la empresa y el local." },
  pl: { metaTitle: "Zaloguj się do TapRadar", metaDescription: "Wszystkie karty lojalnościowe i nagrody w jednej aplikacji.", back: "Powrót do strony", title: "Zaloguj się", intro: "Zaloguj się bezpiecznie swoim adresem e-mail i hasłem.", tabs: { signin: "Logowanie", signup: "Nowe", magic: "Link" }, email: "E-mail", password: "Hasło", passwordPlaceholder: "Co najmniej 8 znaków", show: "Pokaż", hide: "Ukryj", remember: "Nie wylogowuj mnie", forgot: "Nie pamiętasz hasła?", consentBefore: "Akceptuję", privacy: "Politykę prywatności", consentAnd: "oraz", terms: "Regulamin", consentAfter: ".", waiting: "Proszę czekać...", sendLink: "Wyślij link logowania", createAccount: "Utwórz konto", signIn: "Zaloguj się", magicSent: "Link logowania został wysłany. Sprawdź skrzynkę odbiorczą.", accountCreated: "Konto zostało utworzone. Jeśli potrzebne jest potwierdzenie, sprawdź skrzynkę.", unavailable: "Logowanie jest chwilowo niedostępne. Spróbuj ponownie później.", passwordUpdated: "Hasło zostało zmienione. Możesz się teraz zalogować.", legalRequired: "Zaakceptuj Regulamin i Politykę prywatności.", signInFailed: "Logowanie nie powiodło się. E-mail lub hasło są nieprawidłowe.", signupFailed: "Nie udało się utworzyć konta. Sprawdź dane lub spróbuj później.", magicFailed: "Nie udało się wysłać linku. Sprawdź dane lub spróbuj później.", businessTitle: "Utwórz konto firmowe", businessIntro: "Zarejestruj konto sprzedawcy, a następnie skonfiguruj firmę i lokalizację." },
  cs: { metaTitle: "Přihlášení do TapRadar", metaDescription: "Všechny věrnostní karty a odměny v jedné aplikaci.", back: "Zpět na web", title: "Přihlásit se", intro: "Přihlaste se bezpečně e-mailem a heslem.", tabs: { signin: "Přihlášení", signup: "Nový", magic: "Odkaz" }, email: "E-mail", password: "Heslo", passwordPlaceholder: "Alespoň 8 znaků", show: "Zobrazit", hide: "Skrýt", remember: "Zůstat přihlášen", forgot: "Zapomenuté heslo?", consentBefore: "Souhlasím se", privacy: "Zásadami ochrany soukromí", consentAnd: "a", terms: "Podmínkami", consentAfter: ".", waiting: "Čekejte...", sendLink: "Odeslat odkaz", createAccount: "Vytvořit účet", signIn: "Přihlásit se", magicSent: "Přihlašovací odkaz byl odeslán. Zkontrolujte e-mail.", accountCreated: "Účet byl vytvořen. Pokud je třeba potvrzení, zkontrolujte e-mail.", unavailable: "Přihlášení je dočasně nedostupné. Zkuste to později.", passwordUpdated: "Heslo bylo změněno. Nyní se můžete přihlásit.", legalRequired: "Potvrďte Podmínky a Zásady ochrany soukromí.", signInFailed: "Přihlášení se nezdařilo. E-mail nebo heslo není správné.", signupFailed: "Účet se nepodařilo vytvořit. Zkontrolujte údaje nebo to zkuste později.", magicFailed: "Odkaz se nepodařilo odeslat. Zkontrolujte údaje nebo to zkuste později.", businessTitle: "Vytvořit firemní účet", businessIntro: "Zaregistrujte účet obchodníka a poté nastavte firmu a pobočku." },
  hu: { metaTitle: "Bejelentkezés a TapRadarba", metaDescription: "Minden hűségkártya és jutalom egy alkalmazásban.", back: "Vissza a weboldalra", title: "Bejelentkezés", intro: "Jelentkezz be biztonságosan e-mail-címmel és jelszóval.", tabs: { signin: "Belépés", signup: "Új", magic: "Link" }, email: "E-mail", password: "Jelszó", passwordPlaceholder: "Legalább 8 karakter", show: "Mutat", hide: "Elrejt", remember: "Maradjak bejelentkezve", forgot: "Elfelejtetted a jelszót?", consentBefore: "Elfogadom az", privacy: "Adatvédelmi tájékoztatót", consentAnd: "és a", terms: "Feltételeket", consentAfter: ".", waiting: "Kérjük, várj...", sendLink: "Belépési link küldése", createAccount: "Fiók létrehozása", signIn: "Bejelentkezés", magicSent: "A belépési linket elküldtük. Ellenőrizd a postafiókodat.", accountCreated: "A fiók létrejött. Ha megerősítés szükséges, ellenőrizd a postafiókodat.", unavailable: "A bejelentkezés jelenleg nem érhető el. Próbáld újra később.", passwordUpdated: "A jelszavad megváltozott. Most már bejelentkezhetsz.", legalRequired: "Fogadd el a Feltételeket és az Adatvédelmi tájékoztatót.", signInFailed: "A bejelentkezés sikertelen. Az e-mail vagy a jelszó hibás.", signupFailed: "A fiókot nem sikerült létrehozni. Ellenőrizd az adatokat vagy próbáld később.", magicFailed: "A linket nem sikerült elküldeni. Ellenőrizd az adatokat vagy próbáld később.", businessTitle: "Üzleti fiók létrehozása", businessIntro: "Regisztráld kereskedői fiókodat, majd állítsd be a vállalkozást és a helyszínt." },
  sk: { metaTitle: "Prihlásenie do TapRadar", metaDescription: "Všetky vernostné karty a odmeny v jednej aplikácii.", back: "Späť na web", title: "Prihlásiť sa", intro: "Prihláste sa bezpečne e-mailom a heslom.", tabs: { signin: "Prihlásenie", signup: "Nový", magic: "Odkaz" }, email: "E-mail", password: "Heslo", passwordPlaceholder: "Aspoň 8 znakov", show: "Zobraziť", hide: "Skryť", remember: "Zostať prihlásený", forgot: "Zabudnuté heslo?", consentBefore: "Súhlasím so", privacy: "Zásadami ochrany súkromia", consentAnd: "a", terms: "Podmienkami", consentAfter: ".", waiting: "Čakajte...", sendLink: "Odoslať odkaz", createAccount: "Vytvoriť účet", signIn: "Prihlásiť sa", magicSent: "Prihlasovací odkaz bol odoslaný. Skontrolujte e-mail.", accountCreated: "Účet bol vytvorený. Ak je potrebné potvrdenie, skontrolujte e-mail.", unavailable: "Prihlásenie je dočasne nedostupné. Skúste to neskôr.", passwordUpdated: "Heslo bolo zmenené. Teraz sa môžete prihlásiť.", legalRequired: "Potvrďte Podmienky a Zásady ochrany súkromia.", signInFailed: "Prihlásenie zlyhalo. E-mail alebo heslo nie je správne.", signupFailed: "Účet sa nepodarilo vytvoriť. Skontrolujte údaje alebo to skúste neskôr.", magicFailed: "Odkaz sa nepodarilo odoslať. Skontrolujte údaje alebo to skúste neskôr.", businessTitle: "Vytvoriť firemný účet", businessIntro: "Zaregistrujte účet obchodníka a potom nastavte firmu a prevádzku." },
  "sr-Latn": { metaTitle: "Prijava na TapRadar", metaDescription: "Sve kartice lojalnosti i nagrade u jednoj aplikaciji.", back: "Nazad na veb-sajt", title: "Prijava", intro: "Prijavite se bezbedno e-poštom i lozinkom.", tabs: { signin: "Prijava", signup: "Novi", magic: "Link" }, email: "E-pošta", password: "Lozinka", passwordPlaceholder: "Najmanje 8 znakova", show: "Prikaži", hide: "Sakrij", remember: "Ostani prijavljen", forgot: "Zaboravili ste lozinku?", consentBefore: "Prihvatam", privacy: "Politiku privatnosti", consentAnd: "i", terms: "Uslove", consentAfter: ".", waiting: "Sačekajte...", sendLink: "Pošalji link za prijavu", createAccount: "Napravi nalog", signIn: "Prijava", magicSent: "Link za prijavu je poslat. Proverite prijemno sanduče.", accountCreated: "Nalog je napravljen. Ako je potrebna potvrda, proverite prijemno sanduče.", unavailable: "Prijava trenutno nije dostupna. Pokušajte ponovo kasnije.", passwordUpdated: "Lozinka je promenjena. Sada se možete prijaviti.", legalRequired: "Prihvatite Uslove i Politiku privatnosti.", signInFailed: "Prijava nije uspela. E-pošta ili lozinka nisu tačni.", signupFailed: "Nalog nije moguće napraviti. Proverite podatke ili pokušajte kasnije.", magicFailed: "Link nije moguće poslati. Proverite podatke ili pokušajte kasnije.", businessTitle: "Napravi poslovni nalog", businessIntro: "Registrujte nalog trgovca, zatim podesite preduzeće i lokaciju." },
  bs: { metaTitle: "Prijava na TapRadar", metaDescription: "Sve kartice lojalnosti i nagrade u jednoj aplikaciji.", back: "Nazad na web stranicu", title: "Prijava", intro: "Prijavite se sigurno e-poštom i lozinkom.", tabs: { signin: "Prijava", signup: "Novi", magic: "Link" }, email: "E-pošta", password: "Lozinka", passwordPlaceholder: "Najmanje 8 znakova", show: "Prikaži", hide: "Sakrij", remember: "Ostani prijavljen", forgot: "Zaboravili ste lozinku?", consentBefore: "Prihvatam", privacy: "Politiku privatnosti", consentAnd: "i", terms: "Uslove", consentAfter: ".", waiting: "Molimo sačekajte...", sendLink: "Pošalji link za prijavu", createAccount: "Kreiraj račun", signIn: "Prijava", magicSent: "Link za prijavu je poslan. Provjerite prijemno sanduče.", accountCreated: "Račun je kreiran. Ako je potrebna potvrda, provjerite prijemno sanduče.", unavailable: "Prijava trenutno nije dostupna. Pokušajte ponovo kasnije.", passwordUpdated: "Lozinka je promijenjena. Sada se možete prijaviti.", legalRequired: "Prihvatite Uslove i Politiku privatnosti.", signInFailed: "Prijava nije uspjela. E-pošta ili lozinka nisu tačni.", signupFailed: "Račun nije moguće kreirati. Provjerite podatke ili pokušajte kasnije.", magicFailed: "Link nije moguće poslati. Provjerite podatke ili pokušajte kasnije.", businessTitle: "Kreiraj poslovni račun", businessIntro: "Registrujte račun trgovca, zatim podesite firmu i lokaciju." },
  hr: { metaTitle: "Prijava na TapRadar", metaDescription: "Sve kartice vjernosti i nagrade u jednoj aplikaciji.", back: "Natrag na web-stranicu", title: "Prijava", intro: "Prijavite se sigurno e-poštom i lozinkom.", tabs: { signin: "Prijava", signup: "Novi", magic: "Poveznica" }, email: "E-pošta", password: "Lozinka", passwordPlaceholder: "Najmanje 8 znakova", show: "Prikaži", hide: "Sakrij", remember: "Ostani prijavljen", forgot: "Zaboravili ste lozinku?", consentBefore: "Prihvaćam", privacy: "Pravila privatnosti", consentAnd: "i", terms: "Uvjete", consentAfter: ".", waiting: "Pričekajte...", sendLink: "Pošalji poveznicu", createAccount: "Izradi račun", signIn: "Prijava", magicSent: "Poveznica je poslana. Provjerite ulaznu poštu.", accountCreated: "Račun je izrađen. Ako je potrebna potvrda, provjerite ulaznu poštu.", unavailable: "Prijava trenutačno nije dostupna. Pokušajte ponovno kasnije.", passwordUpdated: "Lozinka je promijenjena. Sada se možete prijaviti.", legalRequired: "Prihvatite Uvjete i Pravila privatnosti.", signInFailed: "Prijava nije uspjela. E-pošta ili lozinka nisu točni.", signupFailed: "Račun nije moguće izraditi. Provjerite podatke ili pokušajte kasnije.", magicFailed: "Poveznicu nije moguće poslati. Provjerite podatke ili pokušajte kasnije.", businessTitle: "Izradi poslovni račun", businessIntro: "Registrirajte račun trgovca, zatim postavite tvrtku i lokaciju." },
  ro: { metaTitle: "Autentificare TapRadar", metaDescription: "Toate cardurile de fidelitate și recompensele într-o singură aplicație.", back: "Înapoi la site", title: "Autentificare", intro: "Autentifică-te în siguranță cu adresa de e-mail și parola.", tabs: { signin: "Autentificare", signup: "Nou", magic: "Link" }, email: "E-mail", password: "Parolă", passwordPlaceholder: "Cel puțin 8 caractere", show: "Arată", hide: "Ascunde", remember: "Păstrează-mă conectat", forgot: "Ai uitat parola?", consentBefore: "Accept", privacy: "Politica de confidențialitate", consentAnd: "și", terms: "Termenii", consentAfter: ".", waiting: "Vă rugăm să așteptați...", sendLink: "Trimite linkul", createAccount: "Creează cont", signIn: "Autentificare", magicSent: "Linkul a fost trimis. Verifică mesajele primite.", accountCreated: "Contul a fost creat. Dacă este necesară confirmarea, verifică mesajele primite.", unavailable: "Autentificarea nu este disponibilă momentan. Încearcă mai târziu.", passwordUpdated: "Parola a fost schimbată. Acum te poți autentifica.", legalRequired: "Acceptă Termenii și Politica de confidențialitate.", signInFailed: "Autentificarea a eșuat. E-mailul sau parola sunt incorecte.", signupFailed: "Contul nu a putut fi creat. Verifică datele sau încearcă mai târziu.", magicFailed: "Linkul nu a putut fi trimis. Verifică datele sau încearcă mai târziu.", businessTitle: "Creează cont de afaceri", businessIntro: "Înregistrează contul de comerciant, apoi configurează afacerea și locația." },
  bg: { metaTitle: "Вход в TapRadar", metaDescription: "Всички карти за лоялност и награди в едно приложение.", back: "Назад към сайта", title: "Вход", intro: "Влезте сигурно с имейл адрес и парола.", tabs: { signin: "Вход", signup: "Нов", magic: "Линк" }, email: "Имейл", password: "Парола", passwordPlaceholder: "Поне 8 знака", show: "Покажи", hide: "Скрий", remember: "Остани в профила", forgot: "Забравена парола?", consentBefore: "Приемам", privacy: "Политиката за поверителност", consentAnd: "и", terms: "Условията", consentAfter: ".", waiting: "Моля, изчакайте...", sendLink: "Изпрати линк", createAccount: "Създай акаунт", signIn: "Вход", magicSent: "Линкът е изпратен. Проверете входящата си поща.", accountCreated: "Акаунтът е създаден. Ако е нужно потвърждение, проверете пощата си.", unavailable: "Входът временно не е достъпен. Опитайте по-късно.", passwordUpdated: "Паролата е променена. Вече можете да влезете.", legalRequired: "Приемете Условията и Политиката за поверителност.", signInFailed: "Входът е неуспешен. Имейлът или паролата са грешни.", signupFailed: "Акаунтът не може да бъде създаден. Проверете данните или опитайте по-късно.", magicFailed: "Линкът не може да бъде изпратен. Проверете данните или опитайте по-късно.", businessTitle: "Създай бизнес акаунт", businessIntro: "Регистрирайте акаунт на търговец, след което настройте бизнеса и обекта." },
};
