import type { Locale } from "./config";

export const legalNotices: Record<Locale, { title: string; text: string; german: string }> = {
  de: { title: "", text: "", german: "" },
  en: { title: "Translation notice", text: "This translation is provided for orientation only. Only the German version is legally binding.", german: "Open German version" },
  tr: { title: "Çeviri notu", text: "Bu çeviri yalnızca bilgilendirme amaçlıdır. Yalnızca Almanca sürüm hukuken bağlayıcıdır.", german: "Almanca sürümü aç" },
  fr: { title: "Note de traduction", text: "Cette traduction est fournie à titre indicatif uniquement. Seule la version allemande fait foi sur le plan juridique.", german: "Ouvrir la version allemande" },
  it: { title: "Nota sulla traduzione", text: "Questa traduzione è fornita solo a scopo informativo. Fa fede esclusivamente la versione in lingua tedesca.", german: "Apri la versione tedesca" },
  es: { title: "Nota de traducción", text: "Esta traducción se ofrece únicamente a título informativo. Solo la versión alemana es jurídicamente vinculante.", german: "Abrir la versión alemana" },
  cs: { title: "Poznámka k překladu", text: "Tento překlad slouží pouze pro orientaci. Právně závazné je výhradně německé znění.", german: "Otevřít německou verzi" },
  sk: { title: "Poznámka k prekladu", text: "Tento preklad slúži iba na orientáciu. Právne záväzné je výlučne nemecké znenie.", german: "Otvoriť nemeckú verziu" },
  "sr-Latn": { title: "Napomena o prevodu", text: "Ovaj prevod služi samo za orijentaciju. Pravno je obavezujuća isključivo nemačka verzija.", german: "Otvori nemačku verziju" },
  bs: { title: "Napomena o prijevodu", text: "Ovaj prijevod služi samo za informaciju. Pravno je obavezujuća isključivo njemačka verzija.", german: "Otvori njemačku verziju" },
  hr: { title: "Napomena o prijevodu", text: "Ovaj prijevod služi samo za informaciju. Pravno je obvezujuća isključivo njemačka verzija.", german: "Otvori njemačku verziju" },
  hu: { title: "Fordítási tájékoztató", text: "Ez a fordítás csak tájékoztató jellegű. Jogilag kizárólag a német változat kötelező érvényű.", german: "Német változat megnyitása" },
  ro: { title: "Notă privind traducerea", text: "Această traducere este oferită doar cu titlu informativ. Numai versiunea germană este obligatorie din punct de vedere juridic.", german: "Deschide versiunea germană" },
  pl: { title: "Informacja o tłumaczeniu", text: "To tłumaczenie ma wyłącznie charakter informacyjny. Prawnie wiążąca jest tylko wersja niemiecka.", german: "Otwórz wersję niemiecką" },
  bg: { title: "Бележка за превода", text: "Този превод е само за информация. Правно обвързваща е единствено немската версия.", german: "Отвори немската версия" },
};

export const legalManualOverrides: Partial<Record<Locale, Record<string, string>>> = {
  ro: {
    Impressum: "Informații juridice", Österreich: "Austria", Kontakt: "Contact", "E-Mail:": "E-mail:", "Unternehmensangaben": "Date despre companie",
    "Unternehmensgegenstand: Digitale Kundenbindungsplattform für lokale Geschäfte": "Obiect de activitate: platformă digitală de fidelizare pentru afaceri locale",
    "UID-Nummer: ATU78882167": "Cod TVA: ATU78882167", "Rechtsform: Gesellschaft mit beschränkter Haftung (GmbH)": "Formă juridică: societate cu răspundere limitată (GmbH)",
    "Firmensitz: Guntramsdorf, Österreich": "Sediu social: Guntramsdorf, Austria", Aufsichtsbehörde: "Autoritate de supraveghere",
    "Bezirkshauptmannschaft Mödling": "Administrația districtuală Mödling", "Zuständige Kammer: Wirtschaftskammer Niederösterreich": "Camera competentă: Camera Economică a Austriei Inferioare",
    Datenschutzerklärung: "Politica de confidențialitate", "Stand: Juni 2025": "Versiune: iunie 2025", "1. Verantwortlicher": "1. Operatorul",
    "TOY GmbH, Dr. Adolf-Schärf-Straße 1/2/24, 2353 Guntramsdorf, Österreich. E-Mail:": "TOY GmbH, Dr. Adolf-Schärf-Straße 1/2/24, 2353 Guntramsdorf, Austria. E-mail:",
    "2. Erhebung und Verarbeitung personenbezogener Daten": "2. Colectarea și prelucrarea datelor cu caracter personal",
    "Wir erheben und verarbeiten personenbezogene Daten nur, soweit dies zur Bereitstellung unserer Dienstleistungen erforderlich ist.": "Colectăm și prelucrăm date cu caracter personal numai în măsura necesară pentru furnizarea serviciilor noastre.",
    "Name und Kontaktdaten": "Nume și date de contact", Unternehmensdaten: "Date despre companie", "Nutzungsdaten der TapRadar-Plattform": "Date de utilizare a platformei TapRadar", "Zahlungsinformationen über Zahlungsdienstleister": "Informații de plată prin furnizori de servicii de plată",
    "3. Zweck der Datenverarbeitung": "3. Scopul prelucrării datelor", "Ihre Daten werden zur Bereitstellung Ihres Kontos, zur Zahlungsabwicklung, für Support und zur Erfüllung gesetzlicher Pflichten verwendet.": "Datele dvs. sunt utilizate pentru furnizarea contului, procesarea plăților, asistență și îndeplinirea obligațiilor legale.",
    "4. GPS und Standortdaten": "4. GPS și date de localizare", "TapRadar verwendet Standortdaten ausschließlich zur Verifizierung von Kundenbesuchen.": "TapRadar utilizează datele de localizare exclusiv pentru verificarea vizitelor clienților.",
    "5. Ihre Rechte": "5. Drepturile dvs.", "Sie haben Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch nach DSGVO.": "Aveți dreptul la informare, rectificare, ștergere, restricționare, portabilitatea datelor și opoziție în conformitate cu RGPD.",
    "Allgemeine Geschäftsbedingungen": "Termeni și condiții generale", "1. Geltungsbereich": "1. Domeniul de aplicare", "Diese AGB gelten für die Nutzung der TapRadar-Plattform durch Geschäftskunden und Nutzer.": "Acești termeni se aplică utilizării platformei TapRadar de către clienți comerciali și utilizatori.",
    "2. Leistungen": "2. Servicii", "TapRadar stellt digitale Stempelkarten, Kundenbindungsfunktionen, Bewertungen, Statistiken und Marketingfunktionen bereit.": "TapRadar oferă carduri digitale cu ștampile, funcții de fidelizare, recenzii, statistici și funcții de marketing.",
    "3. Mitgliedschaften": "3. Abonamente", "Die verfügbaren Mitgliedschaften ergeben sich aus der jeweils aktuellen Preisübersicht.": "Abonamentele disponibile sunt cele indicate în lista de prețuri curentă.", "4. Kündigung": "4. Reziliere", "Mitgliedschaften sind monatlich kündbar, sofern nichts anderes vereinbart wurde.": "Abonamentele pot fi reziliate lunar, dacă nu s-a convenit altfel.",
    "5. Kontakt": "5. Contact", "Bei Fragen erreichen Sie uns unter": "Pentru întrebări ne puteți contacta la", Widerrufsbelehrung: "Instrucțiuni privind retragerea", Widerrufsrecht: "Dreptul de retragere",
    "Verbraucher haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen einen Vertrag zu widerrufen.": "Consumatorii au dreptul să se retragă din contract în termen de paisprezece zile, fără a preciza motivele.", Widerrufsfrist: "Termenul de retragere", "Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag des Vertragsabschlusses.": "Termenul de retragere este de paisprezece zile de la data încheierii contractului.",
    "Ausübung des Widerrufs": "Exercitarea dreptului de retragere", "Um Ihr Widerrufsrecht auszuüben, kontaktieren Sie uns per E-Mail an": "Pentru a vă exercita dreptul de retragere, contactați-ne prin e-mail la", "Folgen des Widerrufs": "Consecințele retragerii", "Wenn Sie diesen Vertrag widerrufen, erstatten wir Ihnen alle erhaltenen Zahlungen nach den gesetzlichen Vorgaben zurück.": "Dacă vă retrageți din acest contract, vă vom rambursa toate plățile primite în conformitate cu cerințele legale.",
  },
  pl: {
    Impressum: "Nota prawna", Österreich: "Austria", Kontakt: "Kontakt", "E-Mail:": "E-mail:", Unternehmensangaben: "Dane przedsiębiorstwa", "Unternehmensgegenstand: Digitale Kundenbindungsplattform für lokale Geschäfte": "Przedmiot działalności: cyfrowa platforma lojalnościowa dla lokalnych firm", "UID-Nummer: ATU78882167": "Numer VAT: ATU78882167", "Rechtsform: Gesellschaft mit beschränkter Haftung (GmbH)": "Forma prawna: spółka z ograniczoną odpowiedzialnością (GmbH)", "Firmensitz: Guntramsdorf, Österreich": "Siedziba: Guntramsdorf, Austria", Aufsichtsbehörde: "Organ nadzorczy", "Bezirkshauptmannschaft Mödling": "Starostwo powiatowe Mödling", "Zuständige Kammer: Wirtschaftskammer Niederösterreich": "Właściwa izba: Izba Gospodarcza Dolnej Austrii",
    Datenschutzerklärung: "Polityka prywatności", "Stand: Juni 2025": "Stan na: czerwiec 2025", "1. Verantwortlicher": "1. Administrator", "TOY GmbH, Dr. Adolf-Schärf-Straße 1/2/24, 2353 Guntramsdorf, Österreich. E-Mail:": "TOY GmbH, Dr. Adolf-Schärf-Straße 1/2/24, 2353 Guntramsdorf, Austria. E-mail:", "2. Erhebung und Verarbeitung personenbezogener Daten": "2. Gromadzenie i przetwarzanie danych osobowych", "Wir erheben und verarbeiten personenbezogene Daten nur, soweit dies zur Bereitstellung unserer Dienstleistungen erforderlich ist.": "Gromadzimy i przetwarzamy dane osobowe wyłącznie w zakresie niezbędnym do świadczenia naszych usług.", "Name und Kontaktdaten": "Imię i dane kontaktowe", Unternehmensdaten: "Dane przedsiębiorstwa", "Nutzungsdaten der TapRadar-Plattform": "Dane dotyczące korzystania z platformy TapRadar", "Zahlungsinformationen über Zahlungsdienstleister": "Informacje płatnicze przekazywane przez dostawców płatności", "3. Zweck der Datenverarbeitung": "3. Cel przetwarzania danych", "Ihre Daten werden zur Bereitstellung Ihres Kontos, zur Zahlungsabwicklung, für Support und zur Erfüllung gesetzlicher Pflichten verwendet.": "Dane są wykorzystywane do obsługi konta, przetwarzania płatności, wsparcia i realizacji obowiązków prawnych.", "4. GPS und Standortdaten": "4. GPS i dane lokalizacyjne", "TapRadar verwendet Standortdaten ausschließlich zur Verifizierung von Kundenbesuchen.": "TapRadar wykorzystuje dane lokalizacyjne wyłącznie do weryfikacji wizyt klientów.", "5. Ihre Rechte": "5. Twoje prawa", "Sie haben Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch nach DSGVO.": "Masz prawo dostępu, sprostowania, usunięcia, ograniczenia, przenoszenia danych i sprzeciwu zgodnie z RODO.",
    "Allgemeine Geschäftsbedingungen": "Ogólne warunki handlowe", "1. Geltungsbereich": "1. Zakres obowiązywania", "Diese AGB gelten für die Nutzung der TapRadar-Plattform durch Geschäftskunden und Nutzer.": "Niniejsze warunki dotyczą korzystania z platformy TapRadar przez klientów biznesowych i użytkowników.", "2. Leistungen": "2. Usługi", "TapRadar stellt digitale Stempelkarten, Kundenbindungsfunktionen, Bewertungen, Statistiken und Marketingfunktionen bereit.": "TapRadar udostępnia cyfrowe karty pieczątkowe, funkcje lojalnościowe, opinie, statystyki i funkcje marketingowe.", "3. Mitgliedschaften": "3. Abonamenty", "Die verfügbaren Mitgliedschaften ergeben sich aus der jeweils aktuellen Preisübersicht.": "Dostępne abonamenty wynikają z aktualnego cennika.", "4. Kündigung": "4. Wypowiedzenie", "Mitgliedschaften sind monatlich kündbar, sofern nichts anderes vereinbart wurde.": "Abonamenty można wypowiedzieć co miesiąc, o ile nie uzgodniono inaczej.", "5. Kontakt": "5. Kontakt", "Bei Fragen erreichen Sie uns unter": "W razie pytań skontaktuj się z nami pod adresem", Widerrufsbelehrung: "Informacja o odstąpieniu", Widerrufsrecht: "Prawo odstąpienia", "Verbraucher haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen einen Vertrag zu widerrufen.": "Konsumenci mają prawo odstąpić od umowy w ciągu czternastu dni bez podawania przyczyny.", Widerrufsfrist: "Termin odstąpienia", "Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag des Vertragsabschlusses.": "Termin odstąpienia wynosi czternaście dni od dnia zawarcia umowy.", "Ausübung des Widerrufs": "Wykonanie prawa odstąpienia", "Um Ihr Widerrufsrecht auszuüben, kontaktieren Sie uns per E-Mail an": "Aby skorzystać z prawa odstąpienia, skontaktuj się z nami e-mailem pod adresem", "Folgen des Widerrufs": "Skutki odstąpienia", "Wenn Sie diesen Vertrag widerrufen, erstatten wir Ihnen alle erhaltenen Zahlungen nach den gesetzlichen Vorgaben zurück.": "W przypadku odstąpienia od umowy zwrócimy wszystkie otrzymane płatności zgodnie z wymogami prawa.",
  },
  bg: {
    Impressum: "Правна информация", Österreich: "Австрия", Kontakt: "Контакт", "E-Mail:": "Имейл:", Unternehmensangaben: "Данни за дружеството", "Unternehmensgegenstand: Digitale Kundenbindungsplattform für lokale Geschäfte": "Предмет на дейност: дигитална платформа за лоялност за местни бизнеси", "UID-Nummer: ATU78882167": "ДДС номер: ATU78882167", "Rechtsform: Gesellschaft mit beschränkter Haftung (GmbH)": "Правна форма: дружество с ограничена отговорност (GmbH)", "Firmensitz: Guntramsdorf, Österreich": "Седалище: Гунтрамсдорф, Австрия", Aufsichtsbehörde: "Надзорен орган", "Bezirkshauptmannschaft Mödling": "Областна администрация Мьодлинг", "Zuständige Kammer: Wirtschaftskammer Niederösterreich": "Компетентна камара: Икономическа камара на Долна Австрия",
    Datenschutzerklärung: "Политика за поверителност", "Stand: Juni 2025": "Версия: юни 2025 г.", "1. Verantwortlicher": "1. Администратор", "TOY GmbH, Dr. Adolf-Schärf-Straße 1/2/24, 2353 Guntramsdorf, Österreich. E-Mail:": "TOY GmbH, Dr. Adolf-Schärf-Straße 1/2/24, 2353 Guntramsdorf, Австрия. Имейл:", "2. Erhebung und Verarbeitung personenbezogener Daten": "2. Събиране и обработване на лични данни", "Wir erheben und verarbeiten personenbezogene Daten nur, soweit dies zur Bereitstellung unserer Dienstleistungen erforderlich ist.": "Събираме и обработваме лични данни само доколкото е необходимо за предоставянето на услугите ни.", "Name und Kontaktdaten": "Име и данни за контакт", Unternehmensdaten: "Данни за дружеството", "Nutzungsdaten der TapRadar-Plattform": "Данни за използването на платформата TapRadar", "Zahlungsinformationen über Zahlungsdienstleister": "Платежна информация чрез доставчици на платежни услуги", "3. Zweck der Datenverarbeitung": "3. Цел на обработването", "Ihre Daten werden zur Bereitstellung Ihres Kontos, zur Zahlungsabwicklung, für Support und zur Erfüllung gesetzlicher Pflichten verwendet.": "Данните ви се използват за предоставяне на акаунта, обработка на плащания, поддръжка и изпълнение на законови задължения.", "4. GPS und Standortdaten": "4. GPS и данни за местоположение", "TapRadar verwendet Standortdaten ausschließlich zur Verifizierung von Kundenbesuchen.": "TapRadar използва данни за местоположение единствено за проверка на посещенията на клиенти.", "5. Ihre Rechte": "5. Вашите права", "Sie haben Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch nach DSGVO.": "Имате право на достъп, коригиране, изтриване, ограничаване, преносимост на данните и възражение съгласно GDPR.",
    "Allgemeine Geschäftsbedingungen": "Общи условия", "1. Geltungsbereich": "1. Обхват", "Diese AGB gelten für die Nutzung der TapRadar-Plattform durch Geschäftskunden und Nutzer.": "Тези условия се прилагат за използването на платформата TapRadar от бизнес клиенти и потребители.", "2. Leistungen": "2. Услуги", "TapRadar stellt digitale Stempelkarten, Kundenbindungsfunktionen, Bewertungen, Statistiken und Marketingfunktionen bereit.": "TapRadar предоставя дигитални карти за печати, функции за лоялност, оценки, статистика и маркетингови функции.", "3. Mitgliedschaften": "3. Абонаменти", "Die verfügbaren Mitgliedschaften ergeben sich aus der jeweils aktuellen Preisübersicht.": "Наличните абонаменти са посочени в актуалния ценоразпис.", "4. Kündigung": "4. Прекратяване", "Mitgliedschaften sind monatlich kündbar, sofern nichts anderes vereinbart wurde.": "Абонаментите могат да се прекратяват ежемесечно, освен ако не е договорено друго.", "5. Kontakt": "5. Контакт", "Bei Fragen erreichen Sie uns unter": "При въпроси се свържете с нас на", Widerrufsbelehrung: "Информация за отказ", Widerrufsrecht: "Право на отказ", "Verbraucher haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen einen Vertrag zu widerrufen.": "Потребителите имат право да се откажат от договора в срок от четиринадесет дни, без да посочват причина.", Widerrufsfrist: "Срок за отказ", "Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag des Vertragsabschlusses.": "Срокът за отказ е четиринадесет дни от датата на сключване на договора.", "Ausübung des Widerrufs": "Упражняване на правото на отказ", "Um Ihr Widerrufsrecht auszuüben, kontaktieren Sie uns per E-Mail an": "За да упражните правото си на отказ, свържете се с нас по имейл на", "Folgen des Widerrufs": "Последици от отказа", "Wenn Sie diesen Vertrag widerrufen, erstatten wir Ihnen alle erhaltenen Zahlungen nach den gesetzlichen Vorgaben zurück.": "Ако се откажете от договора, ще възстановим всички получени плащания съгласно законовите изисквания.",
  },
};

