import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { cancelPrivacyRequest, requestPrivacyAction } from "./actions";

type SearchParams = Promise<{ requested?: string; cancelled?: string; error?: string }>;
export default async function PrivacyPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams;
  const supabase = await createClient();
  const { data: auth } = await supabase.auth.getUser();
  if (!auth.user) redirect("/login?next=/dashboard/privacy");
  const { data: requests } = await supabase.from("privacy_requests").select("id, request_type, status, execute_after, created_at").eq("user_id", auth.user.id).order("created_at", { ascending: false });
  return <main className="min-h-screen bg-slate-950 px-5 py-14 text-white"><section className="mx-auto max-w-4xl"><Link href="/dashboard" className="font-black text-cyan-300">Zurück</Link><h1 className="mt-6 text-5xl font-black">Datenschutz und Konto</h1><p className="mt-3 text-slate-300">Eigene Daten herunterladen oder eine Löschung mit siebentägiger Sicherheitsfrist beantragen.</p>{params.requested ? <p className="mt-6 rounded-2xl bg-emerald-300/10 p-4 text-emerald-100">Anfrage wurde registriert.</p> : null}{params.cancelled ? <p className="mt-6 rounded-2xl bg-emerald-300/10 p-4 text-emerald-100">Löschanfrage wurde storniert.</p> : null}{params.error ? <p className="mt-6 rounded-2xl bg-red-300/10 p-4 text-red-100">Aktion nicht möglich: {params.error}</p> : null}<div className="mt-8 grid gap-6 md:grid-cols-2"><article className="rounded-3xl border border-white/10 bg-white/[0.06] p-6"><h2 className="text-2xl font-black">Datenexport</h2><p className="mt-3 text-sm leading-6 text-slate-300">JSON-Export von Profil, Wallet, Stempeln, Rewards, Mitgliedschaften und Datenschutzanfragen.</p><a href="/api/v1/privacy/export" className="mt-5 inline-flex rounded-xl bg-cyan-300 px-4 py-3 font-black text-slate-950">Daten jetzt herunterladen</a><form action={requestPrivacyAction} className="mt-3"><input type="hidden" name="request_type" value="export"/><button className="text-sm font-black text-cyan-200">Exportanfrage protokollieren</button></form></article><article className="rounded-3xl border border-red-300/20 bg-red-300/[0.05] p-6"><h2 className="text-2xl font-black">Konto löschen</h2><p className="mt-3 text-sm leading-6 text-slate-300">Die Löschung wird sieben Tage vorgemerkt. In dieser Zeit kannst du sie stornieren. Unternehmensinhaber müssen vorher Eigentum übertragen oder das Unternehmen schließen.</p><form action={requestPrivacyAction} className="mt-5"><input type="hidden" name="request_type" value="deletion"/><button className="rounded-xl bg-red-300 px-4 py-3 font-black text-slate-950">Löschung vormerken</button></form></article></div><h2 className="mt-10 text-2xl font-black">Bisherige Anfragen</h2><div className="mt-4 grid gap-3">{(requests ?? []).map((request) => <article key={request.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-white/[0.05] p-4"><div><strong className="capitalize">{request.request_type}</strong><p className="text-sm text-slate-400">{request.status} · {new Date(request.created_at).toLocaleString("de-AT")}{request.execute_after ? ` · frühestens ${new Date(request.execute_after).toLocaleDateString("de-AT")}` : ""}</p></div>{request.status === "requested" ? <form action={cancelPrivacyRequest}><input type="hidden" name="request_id" value={request.id}/><button className="rounded-xl bg-white/10 px-3 py-2 text-sm font-black">Stornieren</button></form> : null}</article>)}</div></section></main>;
}
