"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requirePlatformAdmin } from "@/lib/admin";
import { recordAdminAudit } from "@/lib/admin-audit";
import { createAdminClient } from "@/lib/supabase/admin";
import { isUuid, requiredText } from "@/lib/validation";

export async function resolveAbuseSignal(formData:FormData){const{user}=await requirePlatformAdmin("trust.manage");const id=requiredText(formData.get("id"),40);const status=requiredText(formData.get("status"),20);if(!isUuid(id)||!["investigating","dismissed","confirmed"].includes(status))redirect("/admin/trust?error=invalid");const db=createAdminClient();const{data,error}=await db.from("abuse_signals").update({status,resolved_by:user.id,resolved_at:status==="investigating"?null:new Date().toISOString()}).eq("id",id).select("organization_id").single();if(error)redirect("/admin/trust?error=save");await recordAdminAudit(db,{actorUserId:user.id,organizationId:data.organization_id,action:`admin.abuse.${status}`,entityType:"abuse_signal",entityId:id});revalidatePath("/admin/trust");}
export async function moderateReview(formData:FormData){const{user}=await requirePlatformAdmin("trust.manage");const id=requiredText(formData.get("id"),40);const decision=requiredText(formData.get("decision"),20);const note=requiredText(formData.get("note"),500);if(!isUuid(id)||!["published","hidden","removed"].includes(decision)||(decision!=="published"&&!note))redirect("/admin/trust?error=invalid");const db=createAdminClient();const{data,error}=await db.from("reviews").update({status:decision,moderation_note:note||null,moderated_by:user.id,moderated_at:new Date().toISOString()}).eq("id",id).select("organization_id").single();if(error)redirect("/admin/trust?error=save");await db.from("review_reports").update({status:decision==="published"?"dismissed":"actioned",resolved_by:user.id,resolved_at:new Date().toISOString()}).eq("review_id",id).eq("status","open");await recordAdminAudit(db,{actorUserId:user.id,organizationId:data.organization_id,action:`admin.review.${decision}`,entityType:"review",entityId:id,metadata:{note}});revalidatePath("/admin/trust");}
