import Link from "next/link";
import { redirect } from "next/navigation";
import { getDashboardContext } from "@/lib/dashboard";
import { vatLabel,type VatTreatment } from "@/lib/tax";
import { openBillingPortal } from "./actions";

type SearchParams=Promise<{success?:string;cancelled?:string;error?:string}>;
const money=(amount:number,currency="eur")=>new Intl.NumberFormat("de-AT",{style:"currency",currency:currency.toUpperCase()}).format(amount/100);
export default async function BillingPage({searchParams}:{searchParams:SearchParams}) {
  const params=await searchParams;const{supabase,user,organizationId,role}=await getDashboardContext();if(!user)redirect("/login?next=/dashboard/billing");if(!organizationId)redirect("/dashboard/onboarding");
  const[{data:subscription},{data:organization},{data:invoices},{data:products}]=await Promise.all([supabase.from("subscriptions").select("plan,status,product_id,current_period_end,cancel_at_period_end,stripe_customer_id").eq("organization_id",organizationId).maybeSingle(),supabase.from("organizations").select("billing_country_code,tax_id,vat_treatment").eq("id",organizationId).single(),supabase.from("billing_invoices").select("id,invoice_number,status,currency,subtotal_amount,tax_amount,total_amount,issued_at,paid_at,hosted_invoice_url,invoice_pdf_url,vat_treatment").eq("organization_id",organizationId).order("issued_at",{ascending:false}).limit(100),supabase.from("subscription_products").select("id,code,name,description,gross_amount,currency,vat_rate,billing_interval,location_limit,staff_limit,media_limit,features").eq("is_active",true).order("sort_order")]);
  const treatment=(organization?.vat_treatment??"domestic") as VatTreatment;
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_right,#0b4f63_0%,#061827_35%,#020617_100%)] px-5 py-16 text-white sm:px-8"><section className="mx-auto max-w-6xl"><Link href="/dashboard" className="font-black text-cyan-300">Zurück</Link><div className="mt-6 flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-5xl font-black">Tarif und Rechnungen</h1><p className="mt-4 text-slate-300">Alle Preise für österreichische Unternehmen inklusive ausgewiesener Umsatzsteuer.</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.07] px-5 py-3"><span className="text-sm text-slate-400">Aktuell: </span><strong className="capitalize">{subscription?.plan??"bronze"} · {subscription?.status??"incomplete"}</strong></div></div><div className="mt-6 rounded-2xl border border-cyan-300/20 bg-cyan-300/[0.07] p-5"><p className="font-black">Voraussichtliche Steuer: {vatLabel(treatment)}</p><p className="mt-2 text-sm leading-6 text-slate-300">Rechnungsland: {organization?.billing_country_code??"AT"}{organization?.tax_id?` · UID ${organization.tax_id}`:" · keine UID hinterlegt"}. Die endgültige Prüfung erfolgt im Stripe-Checkout.</p></div>
    {params.success?<Notice tone="success">Checkout abgeschlossen. Der Tarif wird nach Stripe-Bestätigung aktiviert.</Notice>:null}{params.cancelled?<Notice>Checkout wurde abgebrochen.</Notice>:null}{params.error?<Notice tone="error">Abrechnung ist noch nicht vollständig konfiguriert ({params.error}).</Notice>:null}
    <div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{(products??[]).map(product=>{const net=Math.round(product.gross_amount/(1+Number(product.vat_rate)/100));const features=Array.isArray(product.features)?product.features.filter(value=>typeof value==="string") as string[]:[];const active=(subscription?.product_id===product.id||subscription?.plan===product.code)&&subscription?.status==="active";return <article key={product.id} className={`rounded-[28px] border p-6 ${subscription?.product_id===product.id||subscription?.plan===product.code?"border-cyan-300/50 bg-cyan-300/[0.08]":"border-white/10 bg-white/[0.07]"}`}><h2 className="text-2xl font-black">{product.name}</h2><p className="mt-3 text-3xl font-black">{money(product.gross_amount,product.currency)}<span className="text-sm text-slate-400"> / {product.billing_interval==="year"?"Jahr":"Monat"}</span></p><p className="mt-1 text-xs text-slate-400">inkl. {product.vat_rate}% USt. · netto {money(net,product.currency)}</p><p className="mt-4 text-sm leading-6 text-slate-300">{product.description}</p><ul className="mt-4 grid gap-2 text-sm text-slate-300"><li>✓ {product.location_limit} Filiale(n)</li><li>✓ {product.staff_limit} Mitarbeiter</li>{features.slice(0,4).map(feature=><li key={feature}>✓ {feature}</li>)}</ul>{role==="owner"?(active?<span className="mt-6 block w-full rounded-2xl bg-emerald-300/15 px-4 py-3 text-center font-black text-emerald-200">Aktiver Tarif</span>:<Link href={`/dashboard/billing/checkout?plan=${encodeURIComponent(product.code)}`} className="mt-6 block w-full rounded-2xl bg-cyan-300 px-4 py-3 text-center font-black text-slate-950">Tarif wählen</Link>):null}</article>})}</div>
    {role==="owner"&&subscription?.stripe_customer_id?<form action={openBillingPortal} className="mt-8"><button className="rounded-2xl border border-white/15 bg-white/[0.07] px-5 py-3 font-black text-cyan-200">Zahlungsmittel, UID und Kündigung verwalten</button></form>:null}{subscription?.current_period_end?<p className="mt-5 text-sm text-slate-400">Aktuelle Periode bis {new Date(subscription.current_period_end).toLocaleDateString("de-AT")}{subscription.cancel_at_period_end?" · Kündigung vorgemerkt":""}</p>:null}
    <section className="mt-12"><h2 className="text-3xl font-black">Rechnungsarchiv</h2><p className="mt-2 text-slate-400">Bezahlte und offene Rechnungen können jederzeit als professionelle TapRadar-PDF geladen werden.</p><div className="mt-5 overflow-x-auto rounded-3xl border border-white/10"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-white/[0.08] text-slate-300"><tr><th className="p-4">Rechnung</th><th className="p-4">Datum</th><th className="p-4">Netto</th><th className="p-4">USt.</th><th className="p-4">Gesamt</th><th className="p-4">Status</th><th className="p-4">Download</th></tr></thead><tbody>{(invoices??[]).map(invoice=><tr key={invoice.id} className="border-t border-white/10"><td className="p-4 font-bold">{invoice.invoice_number??invoice.id}</td><td className="p-4">{invoice.issued_at?new Date(invoice.issued_at).toLocaleDateString("de-AT"):"–"}</td><td className="p-4">{money(invoice.subtotal_amount,invoice.currency)}</td><td className="p-4">{money(invoice.tax_amount,invoice.currency)}</td><td className="p-4 font-black">{money(invoice.total_amount,invoice.currency)}</td><td className="p-4 capitalize">{invoice.status}</td><td className="p-4"><div className="flex flex-wrap gap-3"><a href={`/api/billing/invoices/${invoice.id}/pdf`} className="font-black text-cyan-300">TapRadar PDF</a>{invoice.hosted_invoice_url?<a href={invoice.hosted_invoice_url} target="_blank" rel="noreferrer" className="font-black text-cyan-300">Stripe</a>:null}{invoice.invoice_pdf_url?<a href={invoice.invoice_pdf_url} target="_blank" rel="noreferrer" className="font-black text-cyan-300">Stripe PDF</a>:null}</div></td></tr>)}{!invoices?.length?<tr><td colSpan={7} className="p-6 text-center text-slate-400">Noch keine Rechnung vorhanden.</td></tr>:null}</tbody></table></div></section>
  </section></main>;
}
function Notice({children,tone="warning"}:{children:React.ReactNode;tone?:"success"|"warning"|"error"}){const style=tone==="success"?"bg-emerald-300/10 text-emerald-100":tone==="error"?"bg-red-300/10 text-red-100":"bg-amber-300/10 text-amber-100";return <p className={`mt-7 rounded-2xl p-4 ${style}`}>{children}</p>}
