import { createHash } from "crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";
import { requirePlatformAdminSession } from "@/lib/admin";
import { recordAdminAudit } from "@/lib/admin-audit";
import { decryptIntegrationSecret } from "@/lib/integration-secrets";
import { createAdminClient } from "@/lib/supabase/admin";
import { verifyTotp } from "@/lib/totp";

export async function POST(request:Request){let body:{code?:unknown};try{body=await request.json()}catch{return NextResponse.json({error:"invalid"},{status:400})}const code=typeof body.code==="string"?body.code:"";if(!/^\d{6}$/.test(code))return NextResponse.json({error:"invalid"},{status:400});const{supabase,user}=await requirePlatformAdminSession();const service=createAdminClient();const key=createHash("sha256").update(user.id).digest("hex");const{data:limited,error:limitError}=await service.rpc("consume_rate_limit",{rate_bucket:"admin-mfa",rate_key_hash:key,maximum_requests:8,window_seconds:300});const limit=Array.isArray(limited)?limited[0]:limited;if(limitError||!limit?.allowed)return NextResponse.json({error:"limit"},{status:429});const{data:factor}=await service.from("admin_mfa_factors").select("secret_ciphertext,verified_at,last_used_step").eq("user_id",user.id).maybeSingle();if(!factor)return NextResponse.json({error:"missing"},{status:409});let secret:string|null=null;try{secret=decryptIntegrationSecret(factor.secret_ciphertext)}catch{return NextResponse.json({error:"unavailable"},{status:503})}if(!secret)return NextResponse.json({error:"unavailable"},{status:503});const step=verifyTotp(secret,code);if(step==null||factor.last_used_step!=null&&step<=factor.last_used_step)return NextResponse.json({error:"code"},{status:403});const sessionId=await currentSessionId(supabase);if(!sessionId)return NextResponse.json({error:"session"},{status:401});const now=new Date().toISOString();const{data:updated,error}=await service.from("admin_mfa_factors").update({verified_at:factor.verified_at??now,last_used_step:step,updated_at:now}).eq("user_id",user.id).or(`last_used_step.is.null,last_used_step.lt.${step}`).select("user_id").maybeSingle();if(error||!updated)return NextResponse.json({error:"code"},{status:403});const sessionUpdate=await service.from("admin_sessions").update({mfa_verified_at:now}).eq("session_id",sessionId).eq("user_id",user.id);if(sessionUpdate.error)return NextResponse.json({error:"session"},{status:500});await recordAdminAudit(service,{actorUserId:user.id,action:`admin.security.mfa.${factor.verified_at?"verified":"enrolled"}`,entityType:"mfa_factor",entityId:user.id});return NextResponse.json({ok:true},{headers:{"Cache-Control":"no-store"}})}

async function currentSessionId(supabase:SupabaseClient){const{data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)return null;try{const payload=JSON.parse(Buffer.from(token.split(".")[1],"base64url").toString("utf8")) as {session_id?:unknown};return typeof payload.session_id==="string"&&/^[0-9a-f-]{36}$/i.test(payload.session_id)?payload.session_id:null}catch{return null}}
