import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminDecisionButton } from "@/components/AdminDecisionButton";
import { requirePlatformAdmin } from "@/lib/admin";
import { countryOptions } from "@/lib/tax";
import { assignSubscriptionProduct, deleteAssetAsAdmin, setBusinessApproval, setVatValidation, updateLocationAsAdmin, updateOrganizationAsAdmin } from "../../actions";

type Params=Promise<{id:string}>;type SearchParams=Promise<{saved?:string;error?:string}>;
const money=(amount:number,currency="eur")=>new Intl.NumberFormat("de-AT",{style:"currency",currency:currency.toUpperCase()}).format(amount/100);
export default async function AdminOrganizationPage({params,searchParams}:{params:Params;searchParams:SearchParams}) {
  const{id}=await params;const messages=await searchParams;const{supabase}=await requirePlatformAdmin();
  const[organizationResult,locationsResult,membersResult,cardsResult,offersResult,assetsResult,invoicesResult,auditsResult,productsResult,subscriptionResult]=await Promise.all([
    supabase.from("organizations").select("*").eq("id",id).maybeSingle(),supabase.from("locations").select("*").eq("organization_id",id).order("is_primary",{ascending:false}),supabase.from("organization_members").select("id,user_id,role,is_active,created_at,profiles(email,full_name)").eq("organization_id",id),supabase.from("loyalty_cards").select("id,title,reward_title,earning_rule,verification_instructions,stamps_required,is_active,location_id").eq("organization_id",id),supabase.from("offers").select("id,title,offer_type,discount_type,discount_value,minimum_purchase_amount,redemption_code,conditions,is_active,location_id").eq("organization_id",id),supabase.from("organization_assets").select("id,asset_type,storage_path,mime_type,file_size,alt_text,is_public,created_at,locations(name)").eq("organization_id",id).order("created_at",{ascending:false}),supabase.from("billing_invoices").select("id,invoice_number,status,currency,subtotal_amount,tax_amount,total_amount,issued_at,invoice_pdf_url,hosted_invoice_url").eq("organization_id",id).order("issued_at",{ascending:false}),supabase.from("audit_logs").select("id,action,entity_type,entity_id,metadata,created_at").eq("organization_id",id).order("created_at",{ascending:false}).limit(100),supabase.from("subscription_products").select("id,code,name,gross_amount,is_active").order("sort_order"),supabase.from("subscriptions").select("plan,status,product_id,stripe_customer_id,stripe_subscription_id,current_period_end").eq("organization_id",id).maybeSingle(),
  ]);
  const organization=organizationResult.data;if(!organization)notFound();const returnTo=`/admin/organizations/${id}`;const currentProduct=subscriptionResult.data?.product_id??organization.subscription_product_id;
  return <main className="min-h-screen bg-slate-950 px-5 py-12 text-white sm:px-8"><section className="mx-auto max-w-7xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/admin" className="font-black text-purple-200">← Alle Unternehmen</Link><h1 className="mt-5 text-4xl font-black">{organization.name}</h1><p className="mt-2 text-slate-400">Unternehmens-ID: {organization.id}</p></div><div className="flex flex-wrap gap-2"><Decision id={id} decision="approve" label="Freigeben" returnTo={returnTo}/><Decision id={id} decision="hide" label="Verbergen" tone="warning" returnTo={returnTo}/><Decision id={id} decision="suspend" label="Sperren" tone="danger" returnTo={returnTo}/></div></div>
    {messages.saved?<p className="mt-6 rounded-2xl bg-emerald-300/10 p-4 text-emerald-100">Änderung gespeichert: {messages.saved}.</p>:null}{messages.error?<p className="mt-6 rounded-2xl bg-red-300/10 p-4 text-red-100">Speichern nicht möglich: {messages.error}.</p>:null}
    <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Status" value={organization.is_active?organization.public_status:"gesperrt"}/><Metric label="Onboarding" value={organization.onboarding_status}/><Metric label="Filialen" value={locationsResult.data?.length??0}/><Metric label="Treuekarten" value={cardsResult.data?.length??0}/><Metric label="Rechnungen" value={invoicesResult.data?.length??0}/></div>
    <details open className="mt-8 rounded-3xl border border-white/10 bg-white/[0.05]"><summary className="cursor-pointer p-6 text-2xl font-black">Unternehmens- und Rechnungsdaten</summary><form action={updateOrganizationAsAdmin} className="grid gap-4 border-t border-white/10 p-6 md:grid-cols-2"><Hidden id={id} returnTo={returnTo}/><Field name="name" label="Markenname" value={organization.name} required/><Field name="legal_name" label="Rechtlicher Firmenname" value={organization.legal_name}/><Field name="category" label="Kategorie" value={organization.category} required/><Field name="billing_email" label="Rechnungs-E-Mail" value={organization.billing_email} type="email"/><Field name="billing_address" label="Firmenadresse" value={organization.billing_address}/><Field name="billing_postal_code" label="PLZ" value={organization.billing_postal_code}/><Field name="billing_city" label="Ort" value={organization.billing_city}/><label className="grid gap-2 text-xs font-black uppercase text-slate-400">Land<select name="billing_country_code" defaultValue={organization.billing_country_code??"AT"} className="rounded-xl bg-slate-900 px-4 py-3 text-base font-normal normal-case">{countryOptions.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label><Field name="registration_number" label="Registernummer" value={organization.registration_number}/><Field name="tax_id" label="UID-/Steuernummer" value={organization.tax_id}/><Field name="website" label="Website" value={organization.website}/><label className="grid gap-2 text-xs font-black uppercase text-slate-400 md:col-span-2">Beschreibung<textarea name="description" defaultValue={organization.description??""} className="min-h-28 rounded-xl bg-slate-900 px-4 py-3 text-base font-normal normal-case"/></label><button className="rounded-xl bg-purple-300 px-5 py-3 font-black text-slate-950 md:col-span-2">Unternehmensdaten speichern</button></form></details>
    <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-white/[0.05] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">UID-Prüfung</h2><p className="mt-2 text-sm text-slate-400">UID: {organization.tax_id??"Nicht angegeben"}</p></div><VatBadge status={organization.vat_validation_status}/></div>{organization.vat_validated_at?<p className="mt-3 text-sm text-slate-400">Geprüft am {new Date(organization.vat_validated_at).toLocaleString("de-AT")}</p>:null}<a href="https://ec.europa.eu/taxation_customs/vies/#/vat-validation" target="_blank" rel="noreferrer" className="mt-4 inline-flex font-black text-purple-200">Offizielle VIES-Prüfung öffnen ↗</a><div className="mt-5 grid gap-3"><form action={setVatValidation} className="grid gap-3"><Hidden id={id} returnTo={returnTo}/><input type="hidden" name="status" value="valid"/><input name="note" placeholder="Prüfnotiz, Firmenname laut VIES" className="rounded-xl bg-slate-900 px-4 py-3"/><AdminDecisionButton label="UID als gültig markieren"/></form><div className="flex gap-2"><form action={setVatValidation}><Hidden id={id} returnTo={returnTo}/><input type="hidden" name="status" value="invalid"/><AdminDecisionButton label="Ungültig markieren" tone="danger"/></form><form action={setVatValidation}><Hidden id={id} returnTo={returnTo}/><input type="hidden" name="status" value="pending"/><AdminDecisionButton label="Prüfung zurücksetzen" tone="warning"/></form></div></div></div>
      <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-6"><h2 className="text-2xl font-black">Tarif zuweisen</h2><p className="mt-2 text-sm text-slate-400">Abo: {subscriptionResult.data?.status??"–"} · Stripe: {subscriptionResult.data?.stripe_subscription_id??"nicht verbunden"}</p><form action={assignSubscriptionProduct} className="mt-5 grid gap-3"><Hidden id={id} returnTo={returnTo}/><select name="product_id" defaultValue={currentProduct??""} className="rounded-xl bg-slate-900 px-4 py-3">{(productsResult.data??[]).map(product=><option key={product.id} value={product.id}>{product.name} · {money(product.gross_amount)}{product.is_active?"":" · inaktiv"}</option>)}</select><button className="rounded-xl bg-purple-300 px-5 py-3 font-black text-slate-950">Tarif speichern</button></form><Link href="/admin/products" className="mt-4 inline-flex font-black text-purple-200">Produkte und Preise verwalten →</Link></div></section>
    <details className="mt-6 rounded-3xl border border-white/10 bg-white/[0.05]"><summary className="cursor-pointer p-6 text-2xl font-black">Filialen ({locationsResult.data?.length??0})</summary><div className="grid gap-5 border-t border-white/10 p-6">{(locationsResult.data??[]).map(location=><form key={location.id} action={updateLocationAsAdmin} className="grid gap-3 rounded-2xl bg-white/[0.04] p-5 md:grid-cols-3"><Hidden id={id} returnTo={returnTo}/><input type="hidden" name="location_id" value={location.id}/><Field name="name" label="Name" value={location.name}/><Field name="address" label="Adresse" value={location.address}/><Field name="postal_code" label="PLZ" value={location.postal_code}/><Field name="city" label="Ort" value={location.city}/><Field name="country_code" label="Land" value={location.country_code}/><Field name="phone" label="Telefon" value={location.phone}/><Field name="email" label="E-Mail" value={location.email}/><Field name="latitude" label="Breitengrad" value={String(location.latitude??"")} type="number" step="any"/><Field name="longitude" label="Längengrad" value={String(location.longitude??"")} type="number" step="any"/><label className="grid gap-2 text-xs font-black uppercase text-slate-400">Sichtbarkeit<select name="public_status" defaultValue={location.public_status} className="rounded-xl bg-slate-900 px-4 py-3 text-base font-normal normal-case"><option value="draft">Entwurf</option><option value="open">Offen</option><option value="closed">Geschlossen</option><option value="hidden">Verborgen</option></select></label><label className="flex items-center gap-2 pt-6"><input name="is_active" type="checkbox" defaultChecked={location.is_active}/> Aktiv</label><button className="rounded-xl bg-purple-300/20 px-4 py-3 font-black text-purple-100 md:col-span-3">Filiale speichern</button></form>)}</div></details>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><InfoList title="Treuekarten & Belohnungen" empty="Keine Treuekarten">{(cardsResult.data??[]).map(card=><article key={card.id} className="rounded-xl bg-white/[0.04] p-4"><strong>{card.title}</strong><p className="mt-1 text-sm text-slate-300">{card.earning_rule??"Keine Voraussetzung"} · {card.stamps_required} Stempel → {card.reward_title}</p><p className="mt-1 text-xs text-slate-500">{card.verification_instructions??"Keine Prüfanweisung"} · {card.is_active?"aktiv":"inaktiv"}</p></article>)}</InfoList><InfoList title="Aktionen & Gutscheine" empty="Keine Einträge">{(offersResult.data??[]).map(offer=><article key={offer.id} className="rounded-xl bg-white/[0.04] p-4"><strong>{offer.title}</strong><p className="mt-1 text-sm text-slate-300">{offer.offer_type}{offer.discount_value?` · ${offer.discount_value}${offer.discount_type==="percentage"?" %":" €"}`:""} {offer.redemption_code?`· Code ${offer.redemption_code}`:""}</p><p className="mt-1 text-xs text-slate-500">{offer.conditions??"Keine Bedingungen"} · {offer.is_active?"aktiv":"inaktiv"}</p></article>)}</InfoList></div>
    <details className="mt-6 rounded-3xl border border-white/10 bg-white/[0.05]"><summary className="cursor-pointer p-6 text-2xl font-black">Dateien und Medien ({assetsResult.data?.length??0})</summary><div className="grid gap-3 border-t border-white/10 p-6">{(assetsResult.data??[]).map(asset=>{const location=Array.isArray(asset.locations)?asset.locations[0]:asset.locations;const url=`${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/business-media/${asset.storage_path}`;return <article key={asset.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl bg-white/[0.04] p-4"><div><strong>{asset.asset_type} · {asset.mime_type}</strong><p className="text-sm text-slate-400">{asset.alt_text??"Ohne Beschreibung"} · {location?.name??"Gesamtes Unternehmen"} · {(asset.file_size/1024).toFixed(0)} KB</p></div><div className="flex gap-3"><a href={url} target="_blank" rel="noreferrer" className="font-black text-purple-200">Öffnen</a><form action={deleteAssetAsAdmin}><Hidden id={id} returnTo={returnTo}/><input type="hidden" name="asset_id" value={asset.id}/><AdminDecisionButton label="Löschen" tone="danger"/></form></div></article>})}{!assetsResult.data?.length?<p className="text-slate-400">Keine Dateien.</p>:null}</div></details>
    <details className="mt-6 rounded-3xl border border-white/10 bg-white/[0.05]"><summary className="cursor-pointer p-6 text-2xl font-black">Rechnungen ({invoicesResult.data?.length??0})</summary><div className="overflow-x-auto border-t border-white/10"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr><th className="p-4">Nummer</th><th className="p-4">Datum</th><th className="p-4">Netto</th><th className="p-4">USt.</th><th className="p-4">Gesamt</th><th className="p-4">Status</th><th className="p-4">Datei</th></tr></thead><tbody>{(invoicesResult.data??[]).map(invoice=><tr key={invoice.id} className="border-t border-white/10"><td className="p-4">{invoice.invoice_number??invoice.id}</td><td className="p-4">{invoice.issued_at?new Date(invoice.issued_at).toLocaleDateString("de-AT"):"–"}</td><td className="p-4">{money(invoice.subtotal_amount,invoice.currency)}</td><td className="p-4">{money(invoice.tax_amount,invoice.currency)}</td><td className="p-4 font-black">{money(invoice.total_amount,invoice.currency)}</td><td className="p-4">{invoice.status}</td><td className="p-4">{invoice.invoice_pdf_url?<a href={invoice.invoice_pdf_url} className="font-black text-purple-200">PDF</a>:"–"}</td></tr>)}</tbody></table></div></details>
    <details className="mt-6 rounded-3xl border border-white/10 bg-white/[0.05]"><summary className="cursor-pointer p-6 text-2xl font-black">Team und Prüfprotokoll</summary><div className="grid gap-6 border-t border-white/10 p-6 lg:grid-cols-2"><div><h3 className="font-black">Mitglieder</h3>{(membersResult.data??[]).map(member=>{const profile=Array.isArray(member.profiles)?member.profiles[0]:member.profiles;return <p key={member.id} className="mt-3 rounded-xl bg-white/[0.04] p-3 text-sm">{profile?.full_name||profile?.email||member.user_id} · <strong>{member.role}</strong> · {member.is_active?"aktiv":"inaktiv"}</p>})}</div><div><h3 className="font-black">Letzte Änderungen</h3>{(auditsResult.data??[]).slice(0,20).map(audit=><p key={audit.id} className="mt-3 border-b border-white/10 pb-3 text-sm"><strong>{audit.action}</strong><br/><span className="text-slate-500">{new Date(audit.created_at).toLocaleString("de-AT")} · {audit.entity_type}</span></p>)}</div></div></details>
  </section></main>;
}
function Hidden({id,returnTo}:{id:string;returnTo:string}){return <><input type="hidden" name="organization_id" value={id}/><input type="hidden" name="return_to" value={returnTo}/></>}
function Decision({id,decision,label,tone="default",returnTo}:{id:string;decision:string;label:string;tone?:"default"|"danger"|"warning";returnTo:string}){return <form action={setBusinessApproval}><Hidden id={id} returnTo={returnTo}/><input type="hidden" name="decision" value={decision}/><AdminDecisionButton label={label} tone={tone}/></form>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-white/10 bg-white/[0.05] p-4"><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-2 text-xl font-black capitalize">{value}</p></div>}
function Field({name,label,value,type="text",required=false,...props}:{name:string;label:string;value?:string|null;type?:string;required?:boolean;[key:string]:unknown}){return <label className="grid gap-2 text-xs font-black uppercase text-slate-400">{label}<input name={name} type={type} required={required} defaultValue={value??""} {...props} className="rounded-xl bg-slate-900 px-4 py-3 text-base font-normal normal-case text-white"/></label>}
function VatBadge({status}:{status:string}){const style=status==="valid"?"bg-emerald-300/15 text-emerald-100":status==="invalid"?"bg-red-300/15 text-red-100":"bg-amber-300/15 text-amber-100";return <span className={`rounded-full px-3 py-1 text-sm font-black ${style}`}>{status==="valid"?"✓ UID gültig":status==="invalid"?"✕ UID ungültig":"UID-Prüfung offen"}</span>}
function InfoList({title,empty,children}:{title:string;empty:string;children:React.ReactNode}){const hasChildren=Array.isArray(children)?children.length>0:Boolean(children);return <section className="rounded-3xl border border-white/10 bg-white/[0.05] p-6"><h2 className="text-2xl font-black">{title}</h2><div className="mt-4 grid gap-3">{hasChildren?children:<p className="text-slate-400">{empty}</p>}</div></section>}
