import Link from "next/link";
import { requirePlatformAdmin } from "@/lib/admin";
import { saveSubscriptionProduct } from "../actions";

type SearchParams=Promise<{saved?:string;error?:string}>;
type Product={id:string;code:string;name:string;description:string|null;gross_amount:number;currency:string;vat_rate:number;billing_interval:string;stripe_price_id:string|null;location_limit:number;staff_limit:number;media_limit:number;features:unknown;is_active:boolean;sort_order:number};
export default async function AdminProductsPage({searchParams}:{searchParams:SearchParams}) {
  const params=await searchParams;const{supabase}=await requirePlatformAdmin();const{data}=await supabase.from("subscription_products").select("*").order("sort_order");const products=(data??[]) as Product[];
  return <main className="min-h-screen bg-slate-950 px-5 py-14 text-white sm:px-8"><section className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/admin" className="font-black text-purple-200">← Administration</Link><h1 className="mt-5 text-5xl font-black">Produkte und Preise</h1><p className="mt-3 max-w-3xl text-slate-400">Tarife, Bruttopreise, Limits und Stripe-Preis-IDs zentral verwalten. Änderungen erscheinen im Geschäfts-Dashboard.</p></div></div>{params.saved?<p className="mt-6 rounded-2xl bg-emerald-300/10 p-4 text-emerald-100">Produkt gespeichert.</p>:null}{params.error?<p className="mt-6 rounded-2xl bg-red-300/10 p-4 text-red-100">Produkt konnte nicht gespeichert werden ({params.error}).</p>:null}
    <div className="mt-8 grid gap-6 xl:grid-cols-[1fr_.72fr]"><div className="grid content-start gap-4">{products.map(product=><details key={product.id} className="rounded-3xl border border-white/10 bg-white/[0.05]"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5"><div><div className="flex items-center gap-3"><h2 className="text-xl font-black">{product.name}</h2><span className={`rounded-full px-3 py-1 text-xs font-black ${product.is_active?"bg-emerald-300/15 text-emerald-100":"bg-slate-300/10 text-slate-400"}`}>{product.is_active?"Aktiv":"Inaktiv"}</span></div><p className="mt-2 text-sm text-slate-400">{formatMoney(product.gross_amount)} inkl. {product.vat_rate}% USt. · {product.location_limit} Filialen · {product.staff_limit} Mitarbeiter</p></div><span className="font-black text-purple-200">Bearbeiten ↓</span></summary><ProductForm product={product}/></details>)}</div><div className="h-fit rounded-3xl border border-purple-300/25 bg-purple-300/[0.06] p-6"><h2 className="text-2xl font-black">Neues Produkt</h2><p className="mt-2 text-sm text-slate-400">Für einen neuen bezahlbaren Tarif muss anschließend eine Stripe-Preis-ID hinterlegt werden.</p><ProductForm/></div></div>
  </section></main>;
}
function ProductForm({product}:{product?:Product}){const features=Array.isArray(product?.features)?product.features.filter(value=>typeof value==="string").join("\n"):"";return <form action={saveSubscriptionProduct} className={`${product?"border-t border-white/10":""} grid gap-4 p-5 md:grid-cols-2`}>{product?<input type="hidden" name="product_id" value={product.id}/>:null}<Field name="code" label="Produktcode" value={product?.code} placeholder="z. B. premium" required readOnly={Boolean(product)}/><Field name="name" label="Name" value={product?.name} required/><label className="grid gap-2 text-xs font-black uppercase text-slate-400 md:col-span-2">Beschreibung<textarea name="description" defaultValue={product?.description??""} className="min-h-20 rounded-xl bg-slate-900 px-4 py-3 text-base font-normal normal-case"/></label><Field name="gross_price" label="Bruttopreis (€)" value={product?(product.gross_amount/100).toFixed(2):""} type="number" min="0" step="0.01" required/><Field name="vat_rate" label="USt. (%)" value={String(product?.vat_rate??20)} type="number" min="0" max="100" step="0.01" required/><label className="grid gap-2 text-xs font-black uppercase text-slate-400">Abrechnung<select name="billing_interval" defaultValue={product?.billing_interval??"month"} className="rounded-xl bg-slate-900 px-4 py-3 text-base font-normal normal-case"><option value="month">Monatlich</option><option value="year">Jährlich</option></select></label><Field name="stripe_price_id" label="Stripe Price ID" value={product?.stripe_price_id} placeholder="price_..."/><Field name="location_limit" label="Filiallimit" value={String(product?.location_limit??1)} type="number" min="1" required/><Field name="staff_limit" label="Mitarbeiterlimit" value={String(product?.staff_limit??1)} type="number" min="1" required/><Field name="media_limit" label="Medien/Kampagnen pro Monat" value={String(product?.media_limit??0)} type="number" min="0"/><Field name="sort_order" label="Sortierung" value={String(product?.sort_order??100)} type="number"/><label className="grid gap-2 text-xs font-black uppercase text-slate-400 md:col-span-2">Leistungen (eine pro Zeile)<textarea name="features" defaultValue={features} className="min-h-28 rounded-xl bg-slate-900 px-4 py-3 text-base font-normal normal-case"/></label><label className="flex items-center gap-2"><input name="is_active" type="checkbox" defaultChecked={product?.is_active??true}/> Für Verkauf aktiv</label><button className="rounded-xl bg-purple-300 px-5 py-3 font-black text-slate-950 md:col-span-2">Produkt speichern</button></form>}
function Field({name,label,value,type="text",required=false,...props}:{name:string;label:string;value?:string|null;type?:string;required?:boolean;[key:string]:unknown}){return <label className="grid gap-2 text-xs font-black uppercase text-slate-400">{label}<input name={name} type={type} defaultValue={value??""} required={required} {...props} className="rounded-xl bg-slate-900 px-4 py-3 text-base font-normal normal-case text-white read-only:opacity-60"/></label>}
function formatMoney(cents:number){return new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR"}).format(cents/100)}
