import Link from "next/link";
import { redirect } from "next/navigation";
import { getDashboardContext } from "@/lib/dashboard";
import { OfferForm, type EditableOffer } from "./OfferForm";

type SearchParams=Promise<{saved?:string;error?:string}>;
type Asset={storage_path:string;mime_type:string;alt_text:string|null};
type Offer=EditableOffer&{organization_assets:Asset|Asset[]|null};
const offerTypes=[{value:"aktion",label:"Aktion",icon:"🔥"},{value:"gutschein",label:"Gutschein",icon:"🎟️"}];

export default async function OffersPage({searchParams}:{searchParams:SearchParams}) {
  const params=await searchParams;const{supabase,user,organizationId}=await getDashboardContext();
  if(!user)redirect("/login?next=/dashboard/offers");if(!organizationId)redirect("/dashboard/onboarding");
  const[{data:offerData},{data:locations}]=await Promise.all([
    supabase.from("offers").select("id,title,description,offer_type,discount_type,discount_value,minimum_purchase_amount,redemption_code,conditions,starts_at,ends_at,is_active,location_id,organization_assets!offers_media_asset_id_fkey(storage_path,mime_type,alt_text)").eq("organization_id",organizationId).order("created_at",{ascending:false}),
    supabase.from("locations").select("id,name").eq("organization_id",organizationId).eq("is_active",true).order("is_primary",{ascending:false}),
  ]);
  const offers=(offerData??[]) as Offer[];
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_right,#0b4f63_0%,#061827_35%,#020617_100%)] px-5 py-16 text-white sm:px-8"><section className="mx-auto max-w-6xl"><Link href="/dashboard" className="font-black text-cyan-300">Zurück zum Dashboard</Link><span className="mt-6 inline-flex rounded-full border border-cyan-300/35 bg-cyan-300/10 px-4 py-2 text-sm font-black text-cyan-300">Kunden-App Inhalte</span><h1 className="mt-5 text-5xl font-black">Aktionen & Gutscheine</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-300">Aktionen informieren. Gutscheine besitzen einen fixen Euro- oder Prozentwert. Verdiente Belohnungen werden separat über Treuekarten verwaltet.</p>
    {params.saved?<p className="mt-7 rounded-2xl bg-emerald-300/10 p-4 text-emerald-100">Eintrag gespeichert.</p>:null}{params.error?<p className="mt-7 rounded-2xl bg-red-300/10 p-4 text-red-100">Speichern nicht möglich. Pflichtfelder, Gutscheinwert oder Datei prüfen (JPG, PNG, WebP oder PDF; maximal 5 MB).</p>:null}
    <div className="mt-8 grid gap-5 md:grid-cols-2"><Link href="/dashboard/offers/new/action" className="group rounded-[28px] border border-orange-300/20 bg-gradient-to-br from-orange-300/10 to-red-400/[0.04] p-6 transition hover:-translate-y-0.5 hover:border-orange-300/45"><span className="text-4xl">🔥</span><h2 className="mt-4 text-2xl font-black">Neue Aktion</h2><p className="mt-2 leading-6 text-slate-300">Zeitlich begrenzte Kampagne, Neuigkeit oder besonderes Angebot ohne festen Gutscheinwert.</p><span className="mt-5 inline-flex font-black text-orange-200">Aktionsformular öffnen →</span></Link><Link href="/dashboard/offers/new/voucher" className="group rounded-[28px] border border-cyan-300/20 bg-gradient-to-br from-cyan-300/10 to-blue-500/[0.04] p-6 transition hover:-translate-y-0.5 hover:border-cyan-300/45"><span className="text-4xl">🎟️</span><h2 className="mt-4 text-2xl font-black">Neuer Gutschein</h2><p className="mt-2 leading-6 text-slate-300">Fester Euro- oder Prozentwert, Mindestkauf, Kassencode und Live-Vorschau für die Kunden-App.</p><span className="mt-5 inline-flex font-black text-cyan-200">Gutscheinformular öffnen →</span></Link></div>
    <h2 className="mt-10 text-3xl font-black">Bestehende Einträge</h2><div className="mt-5 grid content-start gap-4">{offers.map(offer=>{const type=offerTypes.find(item=>item.value===offer.offer_type);const asset=Array.isArray(offer.organization_assets)?offer.organization_assets[0]:offer.organization_assets;const mediaUrl=asset?`${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/business-media/${asset.storage_path}`:null;return <details key={offer.id} className="group rounded-[24px] border border-white/10 bg-white/[0.07]"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5"><div><div className="flex items-center gap-3"><span className="rounded-full bg-white/[0.08] px-3 py-2 text-sm font-black text-cyan-200">{type?.icon} {type?.label}</span><span className={offer.is_active?"text-sm font-black text-emerald-200":"text-sm font-black text-slate-400"}>{offer.is_active?"Aktiv":"Inaktiv"}</span></div><h3 className="mt-3 text-xl font-black">{offer.title}</h3>{offer.offer_type==="gutschein"?<p className="mt-1 text-sm text-slate-300">{offer.discount_type==="percentage"?`${offer.discount_value} % Rabatt`:`${offer.discount_value?.toFixed(2).replace(".",",")} € Gutschein`} · Code {offer.redemption_code}</p>:null}</div><span className="text-sm font-black text-cyan-300 group-open:hidden">Bearbeiten ↓</span><span className="hidden text-sm font-black text-cyan-300 group-open:inline">Minimieren ↑</span></summary><OfferForm offer={offer} locations={locations??[]} mediaUrl={mediaUrl} className="border-t border-white/10 p-5"/></details>})}{offers.length===0?<div className="rounded-[28px] border border-white/10 bg-white/[0.07] p-8"><h3 className="text-2xl font-black">Noch kein Eintrag</h3><p className="mt-3 text-slate-300">Wähle oben „Neue Aktion“ oder „Neuer Gutschein“.</p></div>:null}</div>
  </section></main>;
}
