import Link from "next/link";
import { AdminDecisionButton } from "@/components/AdminDecisionButton";
import { FormSubmitButton } from "@/components/FormSubmitButton";
import { requirePlatformAdmin } from "@/lib/admin";
import { countryOptions } from "@/lib/tax";
import { setBusinessApproval } from "./actions";

type SearchParams=Promise<{saved?:string;error?:string;q?:string;country?:string;status?:string;vat?:string}>;
export default async function AdminPage({searchParams}:{searchParams:SearchParams}) {
  const params=await searchParams;const{supabase,admin}=await requirePlatformAdmin();
  let query=supabase.from("organizations").select("id,name,legal_name,category,billing_email,billing_address,billing_postal_code,billing_city,billing_country_code,tax_id,vat_treatment,vat_validation_status,plan,public_status,onboarding_status,submitted_at,is_active,created_at,locations(id),subscriptions(status)").order("created_at",{ascending:false}).limit(250);
  const search=(params.q??"").trim().replace(/[,().%]/g,"").slice(0,80);if(search)query=query.or(`name.ilike.%${search}%,legal_name.ilike.%${search}%,billing_email.ilike.%${search}%,tax_id.ilike.%${search}%`);
  if(params.country?.match(/^[A-Z]{2}$/))query=query.eq("billing_country_code",params.country);
  if(params.status==="suspended")query=query.eq("is_active",false);else if(["open","hidden"].includes(params.status??""))query=query.eq("public_status",params.status);else if(["review","approved","rejected"].includes(params.status??""))query=query.eq("onboarding_status",params.status);
  if(["pending","valid","invalid","not_required"].includes(params.vat??""))query=query.eq("vat_validation_status",params.vat);
  const[organizations,totalOrganizations,customers,stamps,rewards,invoices]=await Promise.all([query,supabase.from("organizations").select("id",{count:"exact",head:true}),supabase.from("customer_profiles").select("user_id",{count:"exact",head:true}),supabase.from("stamp_events").select("id",{count:"exact",head:true}),supabase.from("reward_entitlements").select("id",{count:"exact",head:true}).eq("status","available"),supabase.from("billing_invoices").select("id",{count:"exact",head:true})]);
  return <main className="min-h-screen bg-slate-950 px-5 py-14 text-white sm:px-8"><section className="mx-auto max-w-7xl">
    <div><span className="rounded-full bg-purple-300/15 px-4 py-2 text-sm font-black text-purple-200">Interner Plattform-Admin · {admin.role}</span><h1 className="mt-5 text-5xl font-black">TapRadar Administration</h1></div>
    {params.saved?<p className="mt-7 rounded-2xl bg-emerald-300/10 p-4 text-emerald-100">Änderung wurde gespeichert.</p>:null}{params.error?<p className="mt-7 rounded-2xl bg-red-300/10 p-4 text-red-100">Aktion konnte nicht ausgeführt werden ({params.error}).</p>:null}
    <div className="mt-8 grid gap-4 md:grid-cols-5"><Metric label="Unternehmen" value={totalOrganizations.count??0}/><Metric label="Kunden" value={customers.count??0}/><Metric label="Stempel" value={stamps.count??0}/><Metric label="Offene Rewards" value={rewards.count??0}/><Metric label="Rechnungen" value={invoices.count??0}/></div>
    <form className="mt-10 grid gap-3 rounded-3xl border border-white/10 bg-white/[0.05] p-5 md:grid-cols-5"><label className="grid gap-2 text-xs font-black uppercase text-slate-400 md:col-span-2">Unternehmen suchen<input name="q" defaultValue={params.q??""} placeholder="Name, E-Mail oder UID" className="rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-base font-normal normal-case text-white"/></label><Select label="Land" name="country" value={params.country}><option value="">Alle Länder</option>{countryOptions.map(([code,name])=><option key={code} value={code}>{name}</option>)}</Select><Select label="Status" name="status" value={params.status}><option value="">Alle Status</option><option value="review">In Prüfung</option><option value="approved">Freigegeben</option><option value="open">Öffentlich</option><option value="hidden">Verborgen</option><option value="rejected">Abgelehnt</option><option value="suspended">Gesperrt</option></Select><Select label="UID-Prüfung" name="vat" value={params.vat}><option value="">Alle UID-Status</option><option value="pending">Offen</option><option value="valid">Gültig</option><option value="invalid">Ungültig</option><option value="not_required">Nicht erforderlich</option></Select><div className="flex gap-3 md:col-span-5"><FormSubmitButton label="Filter anwenden" pendingLabel="Filter wird angewendet …" className="rounded-xl bg-purple-300 px-5 py-3 font-black text-slate-950"/><Link href="/admin" className="rounded-xl bg-white/10 px-5 py-3 font-black">Zurücksetzen</Link></div></form>
    <section className="mt-10"><div className="flex items-end justify-between gap-4"><div><h2 className="text-3xl font-black">Unternehmen</h2><p className="mt-2 text-sm text-slate-400">{organizations.data?.length??0} Treffer. Unternehmen anklicken, um alle Daten zu prüfen und zu ändern.</p></div></div><div className="mt-5 grid gap-4">{(organizations.data??[]).map(organization=>{const subscription=first(organization.subscriptions);return <article key={organization.id} className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 transition hover:border-purple-300/35"><div className="flex flex-wrap items-start justify-between gap-4"><Link href={`/admin/organizations/${organization.id}`} className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><h3 className="text-xl font-black hover:text-purple-200">{organization.name}</h3><VatBadge status={organization.vat_validation_status}/>{!organization.is_active?<span className="rounded-full bg-red-300/15 px-3 py-1 text-xs font-black text-red-100">Gesperrt</span>:null}</div><p className="mt-1 text-sm text-slate-400">{organization.legal_name??organization.name} · {organization.category} · {organization.locations?.length??0} Filiale(n)</p><p className="mt-2 text-sm">{organization.billing_address??"Keine Adresse"}, {organization.billing_postal_code??""} {organization.billing_city??""} · {organization.billing_country_code}</p><p className="mt-1 text-sm text-slate-300">{organization.billing_email??"Keine Rechnungs-E-Mail"} · UID: {organization.tax_id??"–"}</p><p className="mt-2 text-sm">Onboarding: <strong className="capitalize">{organization.onboarding_status}</strong> · Abo: <strong>{subscription?.status??"–"}</strong> · Sichtbarkeit: <strong>{organization.public_status}</strong></p></Link><div className="flex flex-wrap gap-2"><Decision organizationId={organization.id} decision="approve" label="Freigeben"/><Decision organizationId={organization.id} decision="hide" label="Verbergen" tone="warning"/><Decision organizationId={organization.id} decision="suspend" label="Sperren" tone="danger"/></div></div></article>})}{!organizations.data?.length?<p className="rounded-3xl border border-white/10 p-8 text-center text-slate-400">Keine Unternehmen mit diesen Filtern gefunden.</p>:null}</div></section>
  </section></main>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-3xl border border-white/10 bg-white/[0.06] p-6"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-4xl font-black">{value}</p></div>}
function Select({label,name,value,children}:{label:string;name:string;value?:string;children:React.ReactNode}){return <label className="grid gap-2 text-xs font-black uppercase text-slate-400">{label}<select name={name} defaultValue={value??""} className="rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-base font-normal normal-case text-white">{children}</select></label>}
function Decision({organizationId,decision,label,tone="default"}:{organizationId:string;decision:string;label:string;tone?:"default"|"danger"|"warning"}){return <form action={setBusinessApproval}><input type="hidden" name="organization_id" value={organizationId}/><input type="hidden" name="decision" value={decision}/><input type="hidden" name="return_to" value="/admin"/><AdminDecisionButton label={label} tone={tone}/></form>}
function VatBadge({status}:{status:string}){const style=status==="valid"?"bg-emerald-300/15 text-emerald-100":status==="invalid"?"bg-red-300/15 text-red-100":"bg-amber-300/15 text-amber-100";return <span className={`rounded-full px-3 py-1 text-xs font-black ${style}`}>UID {status==="valid"?"gültig":status==="invalid"?"ungültig":"offen"}</span>}
function first<T>(value:T|T[]|null|undefined):T|undefined{return Array.isArray(value)?value[0]:value??undefined}
