import { ApiKeyCreator } from "@/components/ApiKeyCreator";
import { requirePlatformAdmin } from "@/lib/admin";
import { revokePlatformApiKey } from "./actions";

type SearchParams=Promise<{saved?:string;error?:string}>;
export default async function AdminApiKeysPage({searchParams}:{searchParams:SearchParams}) { const params=await searchParams;const{supabase}=await requirePlatformAdmin();const{data:keys}=await supabase.from("platform_api_keys").select("id,name,key_prefix,scopes,is_active,expires_at,last_used_at,created_at").order("created_at",{ascending:false});const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL;return <main className="min-h-screen bg-slate-950 px-5 py-14 text-white sm:px-8"><section className="mx-auto max-w-6xl"><p className="text-sm font-black text-purple-200">Interne Konfiguration</p><h1 className="mt-3 text-5xl font-black">API-Schlüssel & Supabase</h1><p className="mt-4 text-slate-400">Nur Plattform-Admins können Schlüssel erstellen oder widerrufen. Secret Keys werden niemals vollständig in Listen angezeigt.</p>{params.saved?<p className="mt-6 rounded-2xl bg-emerald-300/10 p-4 text-emerald-100">API-Schlüssel wurde widerrufen.</p>:null}{params.error?<p className="mt-6 rounded-2xl bg-red-300/10 p-4 text-red-100">Aktion fehlgeschlagen.</p>:null}
    <div className="mt-8 grid gap-4 md:grid-cols-3"><Status label="Supabase Projekt" value={supabaseUrl?new URL(supabaseUrl).host:"Nicht konfiguriert"} ok={Boolean(supabaseUrl)}/><Status label="Anon / Publishable Key" value={process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?"Konfiguriert":"Fehlt"} ok={Boolean(process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)}/><Status label="Service Role" value={process.env.SUPABASE_SERVICE_ROLE_KEY?"Serverseitig geschützt":"Fehlt"} ok={Boolean(process.env.SUPABASE_SERVICE_ROLE_KEY)}/></div><div className="mt-5 rounded-2xl bg-cyan-300/[0.07] p-5"><p className="font-black text-cyan-100">App-Sync-Endpunkt</p><code className="mt-2 block text-sm text-slate-300">GET /api/v1/sync</code><p className="mt-2 text-sm text-slate-400">App-Benutzer melden sich mit Supabase Auth an. Nach einem Kauf aktualisiert der Stripe-Webhook das Abo; der nächste Sync liefert Tarif und Status an die App.</p></div>
    <div className="mt-8"><ApiKeyCreator/></div><div className="mt-8 overflow-x-auto rounded-3xl border border-white/10"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-white/[0.08]"><tr><th className="p-4">Name</th><th className="p-4">Präfix</th><th className="p-4">Berechtigung</th><th className="p-4">Letzte Nutzung</th><th className="p-4">Status</th><th className="p-4"></th></tr></thead><tbody>{(keys??[]).map(key=><tr key={key.id} className="border-t border-white/10"><td className="p-4 font-black">{key.name}<p className="text-xs text-slate-500">{new Date(key.created_at).toLocaleDateString("de-AT")}</p></td><td className="p-4 font-mono">{key.key_prefix}••••••••</td><td className="p-4">{key.scopes.join(", ")}</td><td className="p-4">{key.last_used_at?new Date(key.last_used_at).toLocaleString("de-AT"):"Noch nie"}</td><td className="p-4">{key.is_active?"Aktiv":"Widerrufen"}{key.expires_at?<p className="text-xs text-slate-500">bis {new Date(key.expires_at).toLocaleDateString("de-AT")}</p>:null}</td><td className="p-4">{key.is_active?<form action={revokePlatformApiKey}><input type="hidden" name="key_id" value={key.id}/><button className="rounded-xl bg-red-300/10 px-3 py-2 font-black text-red-200">Widerrufen</button></form>:null}</td></tr>)}{!keys?.length?<tr><td colSpan={6} className="p-8 text-center text-slate-400">Noch keine API-Schlüssel erstellt.</td></tr>:null}</tbody></table></div></section></main>}
function Status({label,value,ok}:{label:string;value:string;ok:boolean}){return <div className="rounded-2xl border border-white/10 bg-white/[0.05] p-5"><p className="text-sm text-slate-400">{label}</p><p className={`mt-2 font-black ${ok?"text-emerald-200":"text-red-200"}`}>{value}</p></div>}
