import Link from "next/link";
import { FormSubmitButton } from "@/components/FormSubmitButton";
import { requirePlatformAdmin } from "@/lib/admin";
import { replyToContactMessage, updateContactStatus } from "./actions";

type SearchParams = Promise<{ q?: string; status?: string; saved?: string; error?: string }>;

export default async function AdminMessagesPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams;
  const { supabase } = await requirePlatformAdmin();
  const search = (params.q ?? "").trim().replace(/[,().%]/g, "").slice(0, 80);
  let query = supabase.from("contact_messages").select("id,name,email,subject,message,status,admin_response,replied_at,created_at").order("created_at", { ascending: false }).limit(250);
  if (search) query = query.or(`name.ilike.%${search}%,email.ilike.%${search}%,subject.ilike.%${search}%,message.ilike.%${search}%`);
  if (["new", "read", "replied", "closed"].includes(params.status ?? "")) query = query.eq("status", params.status);
  const [{ data: messages }, unread] = await Promise.all([query, supabase.from("contact_messages").select("id", { count: "exact", head: true }).eq("status", "new")]);
  return <main className="min-h-screen bg-slate-950 px-5 py-14 text-white sm:px-8"><section className="mx-auto max-w-6xl">
    <p className="text-sm font-black text-purple-200">Kundenservice</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-5xl font-black">Kontakt-Nachrichten</h1><p className="mt-3 text-slate-400">{unread.count ?? 0} ungelesene Nachricht(en)</p></div><Link href="/admin" className="rounded-xl bg-white/10 px-4 py-3 font-black">Zur Übersicht</Link></div>
    {params.saved ? <p className="mt-6 rounded-2xl bg-emerald-300/10 p-4 text-emerald-100">{params.saved === "reply" ? "Antwort wurde für den E-Mail-Versand vorbereitet." : "Status wurde gespeichert."}</p> : null}
    {params.error ? <p className="mt-6 rounded-2xl bg-red-300/10 p-4 text-red-100">Aktion fehlgeschlagen. Bitte prüfen Sie die Eingabe und die E-Mail-Konfiguration.</p> : null}
    <form className="mt-8 grid gap-3 rounded-3xl border border-white/10 bg-white/[0.05] p-5 md:grid-cols-[1fr_220px_auto]"><label className="grid gap-2 text-xs font-black uppercase text-slate-400">Nachrichten durchsuchen<input name="q" defaultValue={params.q ?? ""} placeholder="Name, E-Mail, Thema oder Inhalt" className="rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-base font-normal normal-case text-white"/></label><label className="grid gap-2 text-xs font-black uppercase text-slate-400">Status<select name="status" defaultValue={params.status ?? ""} className="rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-base font-normal normal-case text-white"><option value="">Alle Status</option><option value="new">Neu</option><option value="read">Gelesen</option><option value="replied">Beantwortet</option><option value="closed">Geschlossen</option></select></label><div className="flex items-end gap-2"><FormSubmitButton label="Filtern" pendingLabel="Filter läuft …" className="rounded-xl bg-purple-300 px-5 py-3 font-black text-slate-950"/><Link href="/admin/messages" className="rounded-xl bg-white/10 px-4 py-3 font-black">Reset</Link></div></form>
    <div className="mt-8 grid gap-4">{(messages ?? []).map(message => <details key={message.id} className={`rounded-3xl border p-5 ${message.status === "new" ? "border-purple-300/40 bg-purple-300/[0.08]" : "border-white/10 bg-white/[0.05]"}`}>
      <summary className="cursor-pointer list-none"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-black">{message.subject}</h2><Status status={message.status}/></div><p className="mt-2 text-sm text-slate-300">{message.name} · <a className="text-cyan-300" href={`mailto:${message.email}`}>{message.email}</a></p></div><time className="text-sm text-slate-500">{new Date(message.created_at).toLocaleString("de-AT")}</time></div><p className="mt-3 line-clamp-2 text-sm leading-6 text-slate-400">{message.message}</p></summary>
      <div className="mt-5 border-t border-white/10 pt-5"><p className="whitespace-pre-wrap leading-7 text-slate-200">{message.message}</p>{message.admin_response ? <div className="mt-5 rounded-2xl bg-emerald-300/[0.08] p-4"><p className="text-xs font-black uppercase text-emerald-200">Ihre Antwort</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{message.admin_response}</p></div> : null}
      <div className="mt-5 flex flex-wrap gap-3">{message.status === "new" ? <form action={updateContactStatus}><input type="hidden" name="message_id" value={message.id}/><button name="status" value="read" className="rounded-xl bg-white/10 px-4 py-2 font-black">Als gelesen markieren</button></form> : null}<form action={updateContactStatus}><input type="hidden" name="message_id" value={message.id}/><button name="status" value="closed" className="rounded-xl bg-white/10 px-4 py-2 font-black">Schließen</button></form></div>
      <form action={replyToContactMessage} className="mt-5 grid gap-3"><input type="hidden" name="message_id" value={message.id}/><label className="grid gap-2 text-xs font-black uppercase text-slate-400">Antwort<textarea name="response" required minLength={2} maxLength={5000} defaultValue={message.admin_response ?? ""} placeholder="Antwort an den Kunden schreiben …" className="min-h-32 rounded-xl bg-slate-900 px-4 py-3 text-base font-normal normal-case text-white"/></label><FormSubmitButton label={message.admin_response ? "Antwort erneut senden" : "Antwort senden"} pendingLabel="Antwort wird vorbereitet …" className="w-fit rounded-xl bg-cyan-300 px-5 py-3 font-black text-slate-950"/></form></div>
    </details>)}{!messages?.length ? <p className="rounded-3xl border border-white/10 p-10 text-center text-slate-400">Keine Nachrichten gefunden.</p> : null}</div>
  </section></main>;
}

function Status({ status }: { status: string }) { const style = status === "new" ? "bg-purple-300/20 text-purple-100" : status === "replied" ? "bg-emerald-300/15 text-emerald-100" : status === "closed" ? "bg-slate-300/10 text-slate-300" : "bg-cyan-300/15 text-cyan-100"; const label = status === "new" ? "Neu" : status === "read" ? "Gelesen" : status === "replied" ? "Beantwortet" : "Geschlossen"; return <span className={`rounded-full px-3 py-1 text-xs font-black ${style}`}>{label}</span>; }
