import Link from "next/link";
import { redirect } from "next/navigation";
import { businessCategories } from "@/lib/businessCategories";
import { getDashboardContext } from "@/lib/dashboard";
import { GeocodeAddressButton } from "@/components/GeocodeAddressButton";
import { countryOptions } from "@/lib/tax";
import { choosePlan, configureLoyalty, createFirstLocation, createOrganization, submitForReview } from "./actions";

type SearchParams = Promise<{ error?: string; saved?: string; submitted?: string; checkout?: string; new?: string }>;
const statusStep: Record<string, number> = { organization: 2, location: 3, loyalty: 4, plan: 5, payment: 6, review: 7, approved: 8, rejected: 7 };

export default async function OnboardingPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams;
  const { supabase, user, organizationId, locationId } = await getDashboardContext();
  if (!user) redirect("/login?next=/dashboard/onboarding");
  const creatingAnother = params.new === "1";
  const { data: organization } = organizationId && !creatingAnother ? await supabase.from("organizations").select("name, onboarding_status, rejection_reason").eq("id", organizationId).single() : { data: null };
  const { data: subscription } = organizationId && !creatingAnother ? await supabase.from("subscriptions").select("plan, status").eq("organization_id", organizationId).maybeSingle() : { data: null };
  const { data: products } = await supabase.from("subscription_products").select("id, code, name, description, gross_amount, currency, location_limit").eq("is_active", true).order("sort_order");
  let step = creatingAnother ? 2 : organization ? statusStep[organization.onboarding_status] ?? 2 : 1;
  if (organization?.onboarding_status === "payment" && ["active", "trialing"].includes(subscription?.status ?? "")) step = 7;

  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_right,#0b4f63_0%,#061827_35%,#020617_100%)] px-5 py-14 text-white sm:px-8"><section className="mx-auto max-w-4xl">
    <div className="flex items-center justify-between gap-4"><Link href="/dashboard" className="font-black text-cyan-300">Dashboard</Link><span className="rounded-full border border-cyan-300/35 bg-cyan-300/10 px-4 py-2 text-sm font-black text-cyan-200">Schritt {step} von 8</span></div>
    <Progress current={step} />
    {params.error ? <p className="mt-6 rounded-2xl border border-red-300/30 bg-red-300/10 p-4 text-red-100">Dieser Schritt konnte nicht abgeschlossen werden ({params.error}). Bitte prüfe die Angaben.</p> : null}
    {step === 1 ? <Step title="Konto und E-Mail" text="Dein Konto ist erstellt. Für die Geschäftsregistrierung muss die E-Mail bestätigt sein."><div className="rounded-2xl bg-white/[0.06] p-5"><p className="font-black">{user.email}</p><p className={`mt-2 text-sm ${user.email_confirmed_at ? "text-emerald-200" : "text-amber-200"}`}>{user.email_confirmed_at ? "✓ E-Mail bestätigt" : "Bitte öffne den Bestätigungslink in deinem Postfach."}</p></div>{user.email_confirmed_at ? <p className="text-sm text-slate-300">Bestätigt – fülle jetzt die Unternehmensdaten aus.</p> : null}<OrganizationForm /></Step> : null}
    {step === 2 ? <Step title="Unternehmensdaten" text="Diese Daten gehören zum Vertragspartner. Filialdaten kommen im nächsten Schritt."><OrganizationForm /></Step> : null}
    {step === 3 ? <Step title="Erste Filiale" text="Trage die Adresse ein. TapRadar ermittelt Breitengrad und Längengrad automatisch für die Kartendarstellung."><form action={createFirstLocation} className="grid gap-5"><div className="grid gap-4 md:grid-cols-2"><Field name="name" label="Filialname" required /><Field name="address" label="Straße und Hausnummer" required /><Field name="postal_code" label="PLZ" required /><Field name="city" label="Ort" required /><CountryField name="country_code" label="Land"/><Field name="phone" label="Telefon" /><Field name="email" label="Filial-E-Mail" type="email" /><GeocodeAddressButton/><Field name="latitude" label="Breitengrad (automatisch)" type="number" step="any" required /><Field name="longitude" label="Längengrad (automatisch)" type="number" step="any" required /></div><WeeklyHours /><Submit>Filiale anlegen</Submit></form></Step> : null}
    {step === 4 ? <Step title="Treuekarte konfigurieren" text="Eine Belohnung wird erst verdient, wenn der Kunde die festgelegte Leistung vollständig erfüllt."><form action={configureLoyalty} className="grid gap-5"><Field name="title" label="Name der Treuekarte" defaultValue="Meine Treuekarte" required /><Field name="earning_rule" label="Voraussetzung pro Stempel" defaultValue="1 teilnahmeberechtigtes Produkt kaufen" required/><Field name="stamps_required" label="Benötigte Stempel" type="number" min="1" max="50" defaultValue="10" required /><Field name="reward_title" label="Verdiente Belohnung" defaultValue="1 Gratis-Produkt" required /><Field name="verification_instructions" label="Prüfung durch das Geschäft" defaultValue="Mitarbeiter prüft den Kaufbeleg und vergibt den Stempel über das TapRadar-Gerät." required/><label className="flex items-center gap-3 rounded-2xl border border-white/10 p-4"><input name="all_locations" type="checkbox" defaultChecked className="h-5 w-5 accent-cyan-300" />Für alle jetzigen und zukünftigen Filialen</label><Submit>Treuekarte speichern</Submit></form></Step> : null}
    {step === 5 ? <Step title="Tarif auswählen" text="Der Tarif gehört zum Unternehmen und bestimmt Filial- und Mitarbeiterlimits."><div className="grid gap-4 md:grid-cols-3">{(products??[]).map(product => <form action={choosePlan} key={product.id} className="rounded-2xl border border-white/10 p-5"><input type="hidden" name="plan" value={product.code}/><h3 className="text-xl font-black">{product.name}</h3><p className="mt-2 text-2xl font-black">{new Intl.NumberFormat("de-AT",{style:"currency",currency:product.currency.toUpperCase()}).format(product.gross_amount/100)}</p><p className="mt-2 text-sm text-slate-300">{product.description} · bis {product.location_limit} Filiale(n)</p><button className="mt-5 w-full rounded-xl bg-cyan-300 px-4 py-3 font-black text-slate-950">Auswählen</button></form>)}</div></Step> : null}
    {step === 6 ? <Step title="Zahlung abschließen" text={`Gewählter Tarif: ${subscription?.plan ?? "bronze"}. Prüfe zuerst Preis, Laufzeit und rechtliche Informationen.`}><Link href={`/dashboard/billing/checkout?plan=${encodeURIComponent(subscription?.plan ?? "bronze")}&onboarding=1`} className="rounded-2xl bg-gradient-to-r from-cyan-300 to-blue-500 px-5 py-4 text-center font-black text-slate-950">Bestellung prüfen</Link><p className="text-sm text-slate-400">Erst nach deiner ausdrücklichen Bestätigung wirst du zu Stripe weitergeleitet.</p></Step> : null}
    {step === 7 ? <Step title={organization?.onboarding_status === "review" ? "Prüfung läuft" : "Zur Prüfung einreichen"} text={organization?.onboarding_status === "review" ? "TapRadar prüft die Unternehmens- und Filialdaten. Bis zur Freigabe bleibt der Eintrag unsichtbar." : "Kontrolliere deine Daten. Nach dem Einreichen kann die TapRadar-Administration das Geschäft freigeben."}>{organization?.onboarding_status === "rejected" ? <p className="rounded-2xl bg-red-300/10 p-4 text-red-100">Rückfrage: {organization.rejection_reason ?? "Bitte Daten prüfen."}</p> : null}{organization?.onboarding_status !== "review" ? <form action={submitForReview}><Submit>Verbindlich zur Prüfung einreichen</Submit></form> : <Link href="/dashboard" className="inline-flex rounded-2xl bg-white/10 px-5 py-3 font-black">Zum Dashboard</Link>}</Step> : null}
    {step === 8 ? <Step title="Freigegeben und veröffentlicht" text="Das Unternehmen und seine freigegebenen Filialen sind jetzt in der TapRadar-App sichtbar."><div className="rounded-2xl bg-emerald-300/10 p-5 text-emerald-100">✓ Prüfung abgeschlossen<br/>✓ App-Veröffentlichung aktiv<br/>✓ Synchronisierung aktiv</div><Link href="/dashboard" className="inline-flex rounded-2xl bg-cyan-300 px-6 py-4 font-black text-slate-950">Dashboard öffnen</Link></Step> : null}
    {!locationId && step > 3 && step < 8 ? <p className="mt-5 text-sm text-amber-200">Hinweis: Es ist noch keine aktive Filiale im Kontext verfügbar.</p> : null}
  </section></main>;
}

function OrganizationForm() { return <form action={createOrganization} className="grid gap-4 md:grid-cols-2"><Field name="name" label="Marken-/Unternehmensname" required/><Field name="legal_name" label="Rechtlicher Firmenname"/><label className="grid gap-2 text-xs font-black uppercase text-slate-300">Kategorie<select name="category" required className="rounded-2xl border border-white/15 bg-[#102235] px-4 py-3 text-base font-normal normal-case text-white">{businessCategories.map(group => <optgroup key={group.group} label={group.group}>{group.options.map(option => <option key={option.value} value={option.value}>{option.icon} {option.value}</option>)}</optgroup>)}</select></label><Field name="billing_email" label="Rechnungs-E-Mail" type="email" required/><Field name="billing_address" label="Firmenadresse (Straße und Hausnummer)" required/><Field name="billing_postal_code" label="PLZ" required/><Field name="billing_city" label="Ort" required/><CountryField name="billing_country_code" label="Land"/><Field name="registration_number" label="Firmenbuch-/Registernummer"/><Field name="tax_id" label="UID-/Steuernummer"/><p className="text-sm leading-6 text-slate-400 md:col-span-2">Die Firmenadresse und UID werden für korrekte Rechnungen und die Umsatzsteuerprüfung verwendet.</p><div className="md:col-span-2"><Submit>Unternehmen speichern</Submit></div></form>; }
function WeeklyHours() { return <fieldset className="rounded-2xl border border-white/10 p-5"><legend className="px-2 font-black">Öffnungszeiten</legend><div className="grid gap-3">{[["monday","Montag"],["tuesday","Dienstag"],["wednesday","Mittwoch"],["thursday","Donnerstag"],["friday","Freitag"],["saturday","Samstag"],["sunday","Sonntag"]].map(([key,label], index) => <div key={key} className="grid grid-cols-[1fr_90px_90px_auto] items-center gap-2 text-sm"><strong>{label}</strong><input name={`${key}_open`} type="time" defaultValue={index < 5 ? "09:00" : "10:00"} className="rounded-lg bg-white/10 p-2"/><input name={`${key}_close`} type="time" defaultValue={index < 5 ? "18:00" : "16:00"} className="rounded-lg bg-white/10 p-2"/><label className="flex gap-1"><input name={`${key}_closed`} type="checkbox" defaultChecked={index === 6}/>zu</label></div>)}</div></fieldset>; }
function Step({ title, text, children }: { title: string; text: string; children: React.ReactNode }) { return <div className="mt-7 rounded-[30px] border border-white/10 bg-white/[0.07] p-6 sm:p-8"><h1 className="text-4xl font-black">{title}</h1><p className="mt-3 mb-7 leading-7 text-slate-300">{text}</p><div className="grid gap-5">{children}</div></div>; }
function Progress({ current }: { current: number }) { return <div className="mt-7 grid grid-cols-8 gap-1">{Array.from({length:8},(_,i) => <div key={i} className={`h-2 rounded-full ${i + 1 <= current ? "bg-cyan-300" : "bg-white/10"}`}/>)}</div>; }
function Submit({ children }: { children: React.ReactNode }) { return <button className="rounded-2xl bg-gradient-to-r from-cyan-300 to-blue-500 px-5 py-4 font-black text-slate-950">{children}</button>; }
function Field({ name, label, type="text", required=false, defaultValue, ...props }: { name:string; label:string; type?:string; required?:boolean; defaultValue?:string; [key:string]: unknown }) { return <label className="grid gap-2 text-xs font-black uppercase text-slate-300">{label}<input name={name} type={type} required={required} defaultValue={defaultValue} {...props} className="rounded-2xl border border-white/15 bg-white/[0.06] px-4 py-3 text-base font-normal normal-case text-white"/></label>; }
function CountryField({name,label}:{name:string;label:string}) { return <label className="grid gap-2 text-xs font-black uppercase text-slate-300">{label}<select name={name} defaultValue="AT" required className="rounded-2xl border border-white/15 bg-[#102235] px-4 py-3 text-base font-normal normal-case text-white">{countryOptions.map(([code,country])=><option key={code} value={code}>{country}</option>)}</select></label>; }
