import Link from "next/link";
import { redirect } from "next/navigation";
import { businessCategories } from "@/lib/businessCategories";
import { getDashboardContext } from "@/lib/dashboard";
import { GeocodeAddressButton } from "@/components/GeocodeAddressButton";
import { countryOptions } from "@/lib/tax";
import { createFirstLocation, createOrganization, resubmitBusinessReview } from "./actions";

type SearchParams = Promise<{ error?: string; saved?: string; submitted?: string; checkout?: string; new?: string }>;
export default async function OnboardingPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams;
  const { supabase, user, organizationId, isApproved } = await getDashboardContext();
  if (!user) redirect("/login?next=/dashboard/onboarding");
  const creatingAnother = params.new === "1" && isApproved;
  const { data: organization } = organizationId && !creatingAnother ? await supabase.from("organizations").select("name, onboarding_status, rejection_reason").eq("id", organizationId).single() : { data: null };
  const { count: locationCount } = organizationId && !creatingAnother ? await supabase.from("locations").select("id", { count: "exact", head: true }).eq("organization_id", organizationId).eq("is_active", true) : { count: 0 };
  const hasLocation = (locationCount ?? 0) > 0;
  const step = creatingAnother ? 2 : !organization ? 1 : organization.onboarding_status === "approved" ? 4 : hasLocation ? 3 : 2;

  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_right,#0b4f63_0%,#061827_35%,#020617_100%)] px-5 py-14 text-white sm:px-8"><section className="mx-auto max-w-4xl">
    <div className="flex items-center justify-between gap-4"><Link href="/dashboard" className="font-black text-cyan-300">Dashboard</Link><span className="rounded-full border border-cyan-300/35 bg-cyan-300/10 px-4 py-2 text-sm font-black text-cyan-200">Schritt {step} von 4</span></div>
    <Progress current={step} />
    {params.error ? <p className="mt-6 rounded-2xl border border-red-300/30 bg-red-300/10 p-4 text-red-100">{onboardingError(params.error)}</p> : null}
    {step === 1 ? <Step title="Konto und E-Mail" text="Dein Konto ist erstellt. Für die Geschäftsregistrierung muss die E-Mail bestätigt sein."><div className="rounded-2xl bg-white/[0.06] p-5"><p className="font-black">{user.email}</p><p className={`mt-2 text-sm ${user.email_confirmed_at ? "text-emerald-200" : "text-amber-200"}`}>{user.email_confirmed_at ? "✓ E-Mail bestätigt" : "Bitte öffne den Bestätigungslink in deinem Postfach."}</p></div>{user.email_confirmed_at ? <p className="text-sm text-slate-300">Bestätigt – fülle jetzt die Unternehmensdaten aus.</p> : null}<OrganizationForm /></Step> : null}
    {step === 2 && creatingAnother ? <Step title="Unternehmensdaten" text="Diese Daten gehören zum neuen Vertragspartner. Filialdaten kommen im nächsten Schritt."><OrganizationForm /></Step> : null}
    {step === 2 && !creatingAnother ? <Step title="Erste Filiale" text="Trage die Adresse ein. TapRadar ermittelt Breitengrad und Längengrad automatisch für die Kartendarstellung."><form action={createFirstLocation} className="grid gap-5"><div className="grid gap-4 md:grid-cols-2"><Field name="name" label="Filialname" required /><Field name="address" label="Straße und Hausnummer" required /><Field name="postal_code" label="PLZ" required /><Field name="city" label="Ort" required /><CountryField name="country_code" label="Land"/><Field name="phone" label="Telefon" /><Field name="email" label="Filial-E-Mail" type="email" /><GeocodeAddressButton/><Field name="latitude" label="Breitengrad (automatisch)" type="number" step="any" required /><Field name="longitude" label="Längengrad (automatisch)" type="number" step="any" required /></div><WeeklyHours /><Submit>Filiale anlegen und Prüfung starten</Submit></form></Step> : null}
    {step === 3 && hasLocation ? <Step title={organization?.onboarding_status === "rejected" ? "Angaben überarbeiten" : "Prüfung läuft"} text="TapRadar prüft jetzt die Unternehmens- und Filialdaten. Bis zur Freigabe bleiben nur Übersicht, Unternehmen und Filialen zugänglich.">{organization?.rejection_reason ? <p className="rounded-2xl bg-red-300/10 p-4 text-red-100">Rückfrage: {organization.rejection_reason}</p> : <div className="rounded-2xl bg-amber-300/10 p-5 text-amber-100">⌛ Freigabe durch die TapRadar-Administration ausstehend</div>}<div className="flex flex-wrap gap-3"><Link href="/dashboard/business" className="rounded-2xl bg-white/10 px-5 py-3 font-black">Unternehmen prüfen</Link><Link href="/dashboard/locations" className="rounded-2xl bg-white/10 px-5 py-3 font-black">Filialen prüfen</Link></div>{organization?.onboarding_status === "rejected" ? <form action={resubmitBusinessReview}><Submit>Erneut zur Prüfung einreichen</Submit></form> : null}</Step> : null}
    {step === 4 ? <Step title="Freigegeben und veröffentlicht" text="Das Unternehmen und seine freigegebenen Filialen sind jetzt in der TapRadar-App sichtbar."><div className="rounded-2xl bg-emerald-300/10 p-5 text-emerald-100">✓ Prüfung abgeschlossen<br/>✓ Portal vollständig freigeschaltet<br/>✓ App-Veröffentlichung aktiv</div><Link href="/dashboard" className="inline-flex rounded-2xl bg-cyan-300 px-6 py-4 font-black text-slate-950">Portal öffnen</Link></Step> : null}
  </section></main>;
}

function OrganizationForm() { return <form action={createOrganization} className="grid gap-4 md:grid-cols-2"><Field name="name" label="Marken-/Unternehmensname" required/><Field name="legal_name" label="Rechtlicher Firmenname" required/><label className="grid gap-2 text-xs font-black uppercase text-slate-300">Kategorie<select name="category" required className="rounded-2xl border border-white/15 bg-[#102235] px-4 py-3 text-base font-normal normal-case text-white">{businessCategories.map(group => <optgroup key={group.group} label={group.group}>{group.options.map(option => <option key={option.value} value={option.value}>{option.icon} {option.value}</option>)}</optgroup>)}</select></label><Field name="billing_email" label="Rechnungs-E-Mail" type="email" required/><Field name="billing_address" label="Firmenadresse (Straße und Hausnummer)" required/><Field name="billing_postal_code" label="PLZ" required/><Field name="billing_city" label="Ort" required/><CountryField name="billing_country_code" label="Land"/><Field name="registration_number" label="Firmenbuch-/Registernummer"/><Field name="tax_id" label="UID-/Steuernummer"/><p className="text-sm leading-6 text-slate-400 md:col-span-2">Für die Firmenprüfung ist mindestens eine Firmenbuch-/Registernummer oder UID-/Steuernummer erforderlich.</p><div className="md:col-span-2"><Submit>Unternehmen speichern</Submit></div></form>; }
function WeeklyHours() { return <fieldset className="rounded-2xl border border-white/10 p-5"><legend className="px-2 font-black">Öffnungszeiten</legend><div className="grid gap-3">{[["monday","Montag"],["tuesday","Dienstag"],["wednesday","Mittwoch"],["thursday","Donnerstag"],["friday","Freitag"],["saturday","Samstag"],["sunday","Sonntag"]].map(([key,label], index) => <div key={key} className="grid grid-cols-[1fr_90px_90px_auto] items-center gap-2 text-sm"><strong>{label}</strong><input name={`${key}_open`} type="time" defaultValue={index < 5 ? "09:00" : "10:00"} className="rounded-lg bg-white/10 p-2"/><input name={`${key}_close`} type="time" defaultValue={index < 5 ? "18:00" : "16:00"} className="rounded-lg bg-white/10 p-2"/><label className="flex gap-1"><input name={`${key}_closed`} type="checkbox" defaultChecked={index === 6}/>zu</label></div>)}</div></fieldset>; }
function Step({ title, text, children }: { title: string; text: string; children: React.ReactNode }) { return <div className="mt-7 rounded-[30px] border border-white/10 bg-white/[0.07] p-6 sm:p-8"><h1 className="text-4xl font-black">{title}</h1><p className="mt-3 mb-7 leading-7 text-slate-300">{text}</p><div className="grid gap-5">{children}</div></div>; }
function Progress({ current }: { current: number }) { return <div className="mt-7 grid grid-cols-4 gap-1">{Array.from({length:4},(_,i) => <div key={i} className={`h-2 rounded-full ${i + 1 <= current ? "bg-cyan-300" : "bg-white/10"}`}/>)}</div>; }
function Submit({ children }: { children: React.ReactNode }) { return <button className="rounded-2xl bg-gradient-to-r from-cyan-300 to-blue-500 px-5 py-4 font-black text-slate-950">{children}</button>; }
function onboardingError(error: string) { if (error === "price-mismatch") return "Der angezeigte Tarifpreis stimmt nicht mit Stripe überein. Der Checkout wurde sicherheitshalber gestoppt und es wurde nichts belastet."; if (error === "config") return "Die Zahlungsabwicklung ist vorübergehend nicht verfügbar. Es wurde nichts belastet."; return `Dieser Schritt konnte nicht abgeschlossen werden (${error}). Bitte prüfe die Angaben.`; }
function Field({ name, label, type="text", required=false, defaultValue, ...props }: { name:string; label:string; type?:string; required?:boolean; defaultValue?:string; [key:string]: unknown }) { return <label className="grid gap-2 text-xs font-black uppercase text-slate-300">{label}<input name={name} type={type} required={required} defaultValue={defaultValue} {...props} className="rounded-2xl border border-white/15 bg-white/[0.06] px-4 py-3 text-base font-normal normal-case text-white"/></label>; }
function CountryField({name,label}:{name:string;label:string}) { return <label className="grid gap-2 text-xs font-black uppercase text-slate-300">{label}<select name={name} defaultValue="AT" required className="rounded-2xl border border-white/15 bg-[#102235] px-4 py-3 text-base font-normal normal-case text-white">{countryOptions.map(([code,country])=><option key={code} value={code}>{country}</option>)}</select></label>; }
