import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { hasCurrentLegalAcceptance } from "@/lib/legal-consent";
import { redirect } from "next/navigation";
import { collectStamp } from "./actions";

type Params = Promise<{ token: string }>; type SearchParams = Promise<{ success?: string; balance?: string; reward?: string; error?: string }>;
export default async function CollectPage({ params, searchParams }: { params: Params; searchParams: SearchParams }) { const { token } = await params; const query = await searchParams; const supabase = await createClient(); const { data } = await supabase.auth.getUser(); const action = collectStamp.bind(null, token);
if (data.user && !(await hasCurrentLegalAcceptance(data.user.id, "account"))) redirect(`/rechtliches?next=${encodeURIComponent(`/collect/${token}`)}`);
return <main className="min-h-screen bg-[radial-gradient(circle_at_top_right,#0b4f63_0%,#061827_35%,#020617_100%)] px-5 py-16 text-white"><section className="mx-auto max-w-lg rounded-[32px] border border-white/10 bg-white/[0.07] p-8 text-center"><p className="text-5xl">📍</p><h1 className="mt-5 text-4xl font-black">TapRadar Stempel</h1>{query.success ? <><p className="mt-6 rounded-2xl border border-emerald-300/30 bg-emerald-300/10 p-5 text-lg font-black text-emerald-100">Stempel erfolgreich gespeichert.</p><p className="mt-4 text-slate-300">Aktueller Stand: {query.balance ?? "0"} Stempel</p>{query.reward ? <p className="mt-4 rounded-2xl bg-amber-300/10 p-4 font-black text-amber-100">Eine neue Belohnung wartet in deiner Wallet!</p> : null}<Link href="/app" className="mt-6 inline-flex rounded-2xl bg-cyan-300 px-5 py-3 font-black text-slate-950">Wallet öffnen</Link></> : <>{query.error ? <p className="mt-6 rounded-2xl border border-red-300/30 bg-red-300/10 p-4 text-red-100">Stempel konnte nicht gebucht werden. Bitte warte kurz oder frage das Personal.</p> : <p className="mt-5 leading-7 text-slate-300">Bestätige den Besuch, um einen sicheren digitalen Stempel zu erhalten.</p>}{data.user ? <form action={action}><button className="mt-7 w-full rounded-2xl bg-gradient-to-r from-cyan-300 to-blue-500 px-5 py-4 text-lg font-black text-slate-950">Stempel sammeln</button></form> : <Link href={`/login?next=${encodeURIComponent(`/collect/${token}`)}`} className="mt-7 inline-flex rounded-2xl bg-cyan-300 px-5 py-4 font-black text-slate-950">Anmelden und sammeln</Link>}</>}</section></main>; }
