"use server";
import { randomUUID } from "crypto";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { getDashboardContext } from "@/lib/dashboard";
import { isUuid, requiredText, slugify } from "@/lib/validation";
const days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"];
function payload(formData:FormData){const status=requiredText(formData.get("public_status"),20);const latitude=Number(formData.get("latitude"));const longitude=Number(formData.get("longitude"));return{name:requiredText(formData.get("name"),120),address:requiredText(formData.get("address"),160),postal_code:requiredText(formData.get("postal_code"),20),city:requiredText(formData.get("city"),100),country_code:requiredText(formData.get("country_code"),2).toUpperCase(),phone:requiredText(formData.get("phone"),40)||null,email:requiredText(formData.get("email"),200)||null,latitude:Number.isFinite(latitude)?latitude:null,longitude:Number.isFinite(longitude)?longitude:null,opening_hours:Object.fromEntries(days.map(day=>[day,formData.get(`${day}_closed`)==="on"?{closed:true}:{closed:false,open:requiredText(formData.get(`${day}_open`),5),close:requiredText(formData.get(`${day}_close`),5)}])),public_status:["draft","open","closed","hidden"].includes(status)?status:"draft",is_active:formData.get("is_active")==="on"};}
function invalid(value:ReturnType<typeof payload>){return !value.name||!value.address||!value.postal_code||!value.city||!/^[A-Z]{2}$/.test(value.country_code)||value.latitude===null||value.longitude===null||value.latitude < -90||value.latitude > 90||value.longitude < -180||value.longitude > 180;}
export async function createLocation(formData:FormData){const context=await getDashboardContext();const value=payload(formData);if(!context.organizationId||!["owner","manager"].includes(context.role??"")||invalid(value))redirect("/dashboard/locations?error=fields");const{data:organization}=await context.supabase.from("organizations").select("slug,plan,subscription_product_id").eq("id",context.organizationId).single();const[{count},{data:product}]=await Promise.all([context.supabase.from("locations").select("id",{count:"exact",head:true}).eq("organization_id",context.organizationId).eq("is_active",true),organization?.subscription_product_id?context.supabase.from("subscription_products").select("location_limit").eq("id",organization.subscription_product_id).maybeSingle():context.supabase.from("subscription_products").select("location_limit").eq("code",organization?.plan??"bronze").maybeSingle()]);if((count??0)>=(product?.location_limit??1))redirect("/dashboard/locations?error=plan-limit");const slug=`${organization?.slug??"filiale"}-${slugify(value.name)||"standort"}-${randomUUID().slice(0,6)}`;const{error}=await context.supabase.from("locations").insert({...value,organization_id:context.organizationId,slug,is_primary:false});if(error)redirect("/dashboard/locations?error=save-failed");revalidatePath("/dashboard");redirect("/dashboard/locations?saved=1");}
export async function updateLocation(formData:FormData){const context=await getDashboardContext();const locationId=requiredText(formData.get("location_id"),40);const value=payload(formData);if(!context.organizationId||!isUuid(locationId)||!["owner","manager"].includes(context.role??"")||invalid(value))redirect("/dashboard/locations?error=fields");const{error}=await context.supabase.from("locations").update(value).eq("id",locationId).eq("organization_id",context.organizationId);if(error)redirect("/dashboard/locations?error=save-failed");revalidatePath("/dashboard");revalidatePath("/dashboard/locations");redirect("/dashboard/locations?saved=1");}
