import Link from "next/link";
import { FormSubmitButton } from "@/components/FormSubmitButton";
import { requirePlatformAdmin } from "@/lib/admin";
import { countryOptions } from "@/lib/tax";
import { InvoiceSettingsForm } from "./InvoiceSettingsForm";

type SearchParams=Promise<{q?:string;country?:string;status?:string;from?:string;to?:string;month?:string;saved?:string;error?:string}>;
const money=(amount:number,currency="eur")=>new Intl.NumberFormat("de-AT",{style:"currency",currency:currency.toUpperCase()}).format(amount/100);
export default async function AdminBillingPage({searchParams}:{searchParams:SearchParams}) {
  const params=await searchParams;const{supabase}=await requirePlatformAdmin();let query=supabase.from("billing_invoices").select("id,organization_id,invoice_number,status,currency,subtotal_amount,tax_amount,total_amount,customer_country_code,vat_treatment,issued_at,paid_at,hosted_invoice_url,invoice_pdf_url,organizations(name,legal_name,billing_email,tax_id)").order("issued_at",{ascending:false}).limit(1000);
  if(params.country?.match(/^[A-Z]{2}$/))query=query.eq("customer_country_code",params.country);if(params.status)query=query.eq("status",params.status);if(params.from?.match(/^\d{4}-\d{2}-\d{2}$/))query=query.gte("issued_at",`${params.from}T00:00:00Z`);if(params.to?.match(/^\d{4}-\d{2}-\d{2}$/))query=query.lte("issued_at",`${params.to}T23:59:59Z`);
  const [{data},{data:settings}]=await Promise.all([query,supabase.from("invoice_settings").select("*").eq("id",true).single()]);const search=(params.q??"").trim().toLocaleLowerCase("de");const invoices=(data??[]).filter(invoice=>{if(!search)return true;const organization=Array.isArray(invoice.organizations)?invoice.organizations[0]:invoice.organizations;return [organization?.name,organization?.legal_name,organization?.billing_email,organization?.tax_id,invoice.invoice_number].some(value=>value?.toLocaleLowerCase("de").includes(search));});const paid=invoices.filter(i=>i.status==="paid");const net=paid.reduce((sum,i)=>sum+i.subtotal_amount,0);const total=paid.reduce((sum,i)=>sum+i.total_amount,0);const taxes=paid.reduce((sum,i)=>sum+i.tax_amount,0);const month=/^\d{4}-(0[1-9]|1[0-2])$/.test(params.month??"")?params.month!:new Date().toISOString().slice(0,7);
  return <main className="min-h-screen bg-slate-950 px-5 py-14 text-white sm:px-8"><section className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/admin" className="font-black text-purple-200">← Administration</Link><h1 className="mt-5 text-5xl font-black">Rechnungsverwaltung</h1><p className="mt-3 text-slate-400">Rechnungsvorlage, Einzelbelege und Monatsabschluss zentral verwalten.</p></div><div className="flex flex-wrap gap-3"><Metric label="Netto verkauft" value={money(net)}/><Metric label="USt. gesamt" value={money(taxes)}/><Metric label="Brutto bezahlt" value={money(total)}/></div></div>
    {params.saved?<p className="mt-6 rounded-2xl bg-emerald-300/10 p-4 text-emerald-100">Rechnungseinstellungen wurden gespeichert.</p>:null}
    <InvoiceSettingsForm settings={settings}/>
    <section className="mt-8 rounded-3xl border border-cyan-300/20 bg-cyan-300/[0.05] p-6"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-widest text-cyan-200">Buchhaltung</p><h2 className="mt-2 text-2xl font-black">Monatsabschluss</h2><p className="mt-2 text-sm text-slate-400">PDF-Auswertung, Excel-kompatible CSV oder ZIP mit allen Einzelrechnungen.</p></div><form className="flex flex-wrap items-end gap-3"><label className="grid gap-2 text-xs font-black uppercase text-slate-400">Monat<input name="month" type="month" defaultValue={month} className="rounded-xl bg-slate-900 px-4 py-3 text-base font-normal normal-case"/></label><FormSubmitButton label="Monat anzeigen" pendingLabel="Wird geladen …" className="rounded-xl bg-white/10 px-4 py-3 font-black"/></form></div><div className="mt-5 flex flex-wrap gap-3"><a href={`/api/admin/billing/monthly-summary?month=${month}&format=pdf`} className="rounded-xl bg-cyan-300 px-4 py-3 font-black text-slate-950">Monatsauswertung PDF</a><a href={`/api/admin/billing/monthly-summary?month=${month}&format=csv`} className="rounded-xl bg-white/10 px-4 py-3 font-black">Buchhaltungs-CSV</a><a href={`/api/admin/billing/monthly-summary?month=${month}&format=zip`} className="rounded-xl bg-purple-300/20 px-4 py-3 font-black text-purple-100">Alle Rechnungen als ZIP</a></div></section>
    <form className="mt-8 grid gap-3 rounded-3xl border border-white/10 bg-white/[0.05] p-5 md:grid-cols-6"><input type="hidden" name="month" value={month}/><label className="grid gap-2 text-xs font-black uppercase text-slate-400 md:col-span-2">Suche<input name="q" defaultValue={params.q??""} placeholder="Unternehmen, E-Mail, UID, Rechnung" className="rounded-xl bg-slate-900 px-4 py-3 text-base font-normal normal-case"/></label><Select label="Land" name="country" value={params.country}><option value="">Alle Länder</option>{countryOptions.map(([code,name])=><option key={code} value={code}>{name}</option>)}</Select><Select label="Status" name="status" value={params.status}><option value="">Alle Status</option>{["draft","open","paid","void","uncollectible"].map(status=><option key={status} value={status}>{status}</option>)}</Select><Field label="Von" name="from" value={params.from} type="date"/><Field label="Bis" name="to" value={params.to} type="date"/><div className="flex gap-3 md:col-span-6"><FormSubmitButton label="Filter anwenden" pendingLabel="Filter wird angewendet …" className="rounded-xl bg-purple-300 px-5 py-3 font-black text-slate-950"/><Link href="/admin/billing" className="rounded-xl bg-white/10 px-5 py-3 font-black">Zurücksetzen</Link></div></form>
    <div className="mt-5 flex items-center justify-between"><p className="text-sm text-slate-400">{invoices.length} Rechnung(en) gefunden</p></div><div className="mt-4 overflow-x-auto rounded-3xl border border-white/10"><table className="w-full min-w-[1080px] text-left text-sm"><thead className="bg-white/[0.08]"><tr><th className="p-4">Unternehmen</th><th className="p-4">Rechnung</th><th className="p-4">Land / Steuer</th><th className="p-4">Netto</th><th className="p-4">USt.</th><th className="p-4">Gesamt</th><th className="p-4">Status</th><th className="p-4">Download</th></tr></thead><tbody>{invoices.map(invoice=>{const organization=Array.isArray(invoice.organizations)?invoice.organizations[0]:invoice.organizations;return <tr key={invoice.id} className="border-t border-white/10 hover:bg-white/[0.03]"><td className="p-4"><Link href={`/admin/organizations/${invoice.organization_id}`} className="font-black text-purple-100 hover:text-purple-300">{organization?.name??"–"}</Link><p className="text-xs text-slate-400">{organization?.billing_email}</p></td><td className="p-4">{invoice.invoice_number??invoice.id}<p className="text-xs text-slate-500">{invoice.issued_at?new Date(invoice.issued_at).toLocaleDateString("de-AT"):"–"}</p></td><td className="p-4">{invoice.customer_country_code??"–"}<p className="text-xs text-slate-400">{invoice.vat_treatment}</p></td><td className="p-4">{money(invoice.subtotal_amount,invoice.currency)}</td><td className="p-4">{money(invoice.tax_amount,invoice.currency)}</td><td className="p-4 font-black">{money(invoice.total_amount,invoice.currency)}</td><td className="p-4 capitalize">{invoice.status}</td><td className="p-4"><div className="flex flex-wrap gap-3"><a href={`/api/billing/invoices/${invoice.id}/pdf`} className="font-black text-cyan-300">TapRadar PDF</a>{invoice.hosted_invoice_url?<a href={invoice.hosted_invoice_url} target="_blank" rel="noreferrer" className="font-black text-purple-200">Stripe</a>:null}{invoice.invoice_pdf_url?<a href={invoice.invoice_pdf_url} target="_blank" rel="noreferrer" className="font-black text-purple-200">Stripe PDF</a>:null}</div></td></tr>})}{!invoices.length?<tr><td colSpan={8} className="p-8 text-center text-slate-400">Keine Rechnungen mit diesen Filtern gefunden.</td></tr>:null}</tbody></table></div>
  </section></main>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-white/[0.06] px-5 py-3"><span className="text-xs text-slate-500">{label}</span><p className="font-black">{value}</p></div>}
function Select({label,name,value,children}:{label:string;name:string;value?:string;children:React.ReactNode}){return <label className="grid gap-2 text-xs font-black uppercase text-slate-400">{label}<select name={name} defaultValue={value??""} className="rounded-xl bg-slate-900 px-4 py-3 text-base font-normal normal-case">{children}</select></label>}
function Field({label,name,value,type="text",required=false}:{label:string;name:string;value?:string|null;type?:string;required?:boolean}){return <label className="grid gap-2 text-xs font-black uppercase text-slate-400">{label}<input required={required} name={name} type={type} defaultValue={value??""} className="rounded-xl bg-slate-900 px-4 py-3 text-base font-normal normal-case"/></label>}
