-- Marketing content is never published or sent before a platform review.

alter table public.offers
  add column if not exists moderation_status text not null default 'pending_review',
  add column if not exists requested_active boolean not null default true,
  add column if not exists submitted_by uuid references auth.users(id) on delete set null,
  add column if not exists submitted_at timestamptz,
  add column if not exists reviewed_by uuid references auth.users(id) on delete set null,
  add column if not exists reviewed_at timestamptz,
  add column if not exists rejection_reason text,
  add column if not exists review_version integer not null default 1;

alter table public.offers drop constraint if exists offers_moderation_status_check;
alter table public.offers add constraint offers_moderation_status_check
  check (moderation_status in ('pending_review', 'approved', 'rejected'));

update public.offers
set moderation_status = case when is_active then 'approved' else 'pending_review' end,
    requested_active = is_active,
    submitted_at = coalesce(submitted_at, created_at)
where submitted_at is null;

create table if not exists public.push_messages (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.organizations(id) on delete cascade,
  location_id uuid references public.locations(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  title text not null,
  body text not null,
  target_type text not null default 'all' check (target_type in ('all','segment','individual')),
  segment_name text,
  moderation_status text not null default 'pending_review'
    check (moderation_status in ('pending_review','approved','rejected')),
  delivery_status text not null default 'awaiting_approval'
    check (delivery_status in ('awaiting_approval','queued','sending','sent','failed','cancelled')),
  submitted_at timestamptz not null default now(),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  rejection_reason text,
  review_version integer not null default 1,
  sent_count integer not null default 0 check (sent_count >= 0),
  opened_count integer not null default 0 check (opened_count >= 0),
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.push_messages
  add column if not exists location_id uuid references public.locations(id) on delete set null,
  add column if not exists created_by uuid references auth.users(id) on delete set null,
  add column if not exists moderation_status text not null default 'pending_review',
  add column if not exists delivery_status text not null default 'awaiting_approval',
  add column if not exists submitted_at timestamptz not null default now(),
  add column if not exists reviewed_by uuid references auth.users(id) on delete set null,
  add column if not exists reviewed_at timestamptz,
  add column if not exists rejection_reason text,
  add column if not exists review_version integer not null default 1;

alter table public.push_messages drop constraint if exists push_messages_moderation_status_check;
alter table public.push_messages add constraint push_messages_moderation_status_check
  check (moderation_status in ('pending_review','approved','rejected'));
alter table public.push_messages drop constraint if exists push_messages_delivery_status_check;
alter table public.push_messages add constraint push_messages_delivery_status_check
  check (delivery_status in ('awaiting_approval','queued','sending','sent','failed','cancelled'));

create index if not exists offers_moderation_queue_idx
  on public.offers (moderation_status, submitted_at desc);
create index if not exists push_messages_moderation_queue_idx
  on public.push_messages (moderation_status, submitted_at desc);

create table if not exists public.admin_notifications (
  id bigint generated by default as identity primary key,
  recipient_user_id uuid not null references auth.users(id) on delete cascade,
  organization_id uuid references public.organizations(id) on delete cascade,
  resource_type text not null check (resource_type in ('offer','push_message')),
  resource_id uuid not null,
  review_version integer not null,
  title text not null,
  body text not null,
  href text not null,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique (recipient_user_id, resource_type, resource_id, review_version)
);

create index if not exists admin_notifications_unread_idx
  on public.admin_notifications (recipient_user_id, created_at desc) where read_at is null;

create or replace function public.queue_marketing_admin_notifications()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  organization_name text;
  kind_label text;
  target_title text;
  target_body text;
  target_href text := '/admin/marketing';
  organization_id_value uuid;
begin
  if tg_table_name = 'offers' then
    if new.moderation_status <> 'pending_review' then return new; end if;
    if tg_op = 'UPDATE' and old.review_version = new.review_version then return new; end if;
    organization_id_value := new.organization_id;
    kind_label := case when new.offer_type = 'gutschein' then 'Gutschein' else 'Aktion' end;
  else
    if new.moderation_status <> 'pending_review' then return new; end if;
    if tg_op = 'UPDATE' and old.review_version = new.review_version then return new; end if;
    organization_id_value := new.business_id;
    kind_label := 'Push-Nachricht';
  end if;

  select name into organization_name from public.organizations where id = organization_id_value;
  target_title := kind_label || ' wartet auf Freigabe';
  target_body := coalesce(organization_name, 'Ein Geschäft') || ' hat „' || new.title || '“ eingereicht.';

  insert into public.admin_notifications
    (recipient_user_id, organization_id, resource_type, resource_id, review_version, title, body, href)
  select pa.user_id, organization_id_value,
    case when tg_table_name = 'offers' then 'offer' else 'push_message' end,
    new.id, new.review_version, target_title, target_body, target_href
  from public.platform_admins pa
  where pa.is_active = true and pa.role in ('super_admin', 'operations')
  on conflict do nothing;
  return new;
end;
$$;

drop trigger if exists offers_queue_admin_review on public.offers;
create trigger offers_queue_admin_review after insert or update on public.offers
for each row execute function public.queue_marketing_admin_notifications();
drop trigger if exists push_messages_queue_admin_review on public.push_messages;
create trigger push_messages_queue_admin_review after insert or update on public.push_messages
for each row execute function public.queue_marketing_admin_notifications();

create or replace function public.enforce_offer_moderation()
returns trigger language plpgsql security definer set search_path = public as $$
declare is_admin boolean := public.is_platform_admin() or auth.role() = 'service_role';
begin
  if is_admin then return new; end if;
  if tg_op = 'INSERT' then
    new.requested_active := new.is_active;
    new.is_active := false;
    new.moderation_status := 'pending_review';
    new.submitted_by := auth.uid();
    new.submitted_at := now();
    new.reviewed_by := null; new.reviewed_at := null; new.rejection_reason := null;
    return new;
  end if;

  if row(new.title,new.description,new.offer_type,new.discount_type,new.discount_value,
         new.minimum_purchase_amount,new.redemption_code,new.conditions,new.media_asset_id,
         new.starts_at,new.ends_at,new.location_id)
     is distinct from
     row(old.title,old.description,old.offer_type,old.discount_type,old.discount_value,
         old.minimum_purchase_amount,old.redemption_code,old.conditions,old.media_asset_id,
         old.starts_at,old.ends_at,old.location_id) then
    new.requested_active := new.is_active or old.requested_active;
    new.is_active := false;
    new.moderation_status := 'pending_review';
    new.submitted_by := auth.uid();
    new.submitted_at := now();
    new.reviewed_by := null; new.reviewed_at := null; new.rejection_reason := null;
    new.review_version := old.review_version + 1;
  else
    new.moderation_status := old.moderation_status;
    new.reviewed_by := old.reviewed_by; new.reviewed_at := old.reviewed_at;
    new.rejection_reason := old.rejection_reason; new.review_version := old.review_version;
    if old.moderation_status <> 'approved' then new.is_active := false; end if;
  end if;
  return new;
end;
$$;

drop trigger if exists offers_enforce_moderation on public.offers;
create trigger offers_enforce_moderation before insert or update on public.offers
for each row execute function public.enforce_offer_moderation();

drop policy if exists "Public can read active offers" on public.offers;
create policy "Public can read approved active offers" on public.offers for select
to anon, authenticated using (
  moderation_status = 'approved' and is_active = true
  and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at >= now())
  and exists (select 1 from public.organizations o where o.id = organization_id and o.is_active and o.public_status = 'open')
  and (location_id is null or exists (select 1 from public.locations l where l.id = location_id and l.is_active and l.public_status in ('open','closed')))
);

alter table public.push_messages enable row level security;
alter table public.admin_notifications enable row level security;

drop policy if exists "Organization members can read push messages" on public.push_messages;
create policy "Organization members can read push messages" on public.push_messages for select to authenticated
using (public.current_organization_role(business_id) is not null or public.is_platform_admin());
drop policy if exists "Organization managers can create push messages" on public.push_messages;
create policy "Organization managers can create push messages" on public.push_messages for insert to authenticated
with check (public.current_organization_role(business_id) in ('owner','manager'));
drop policy if exists "Platform admins can review push messages" on public.push_messages;
create policy "Platform admins can review push messages" on public.push_messages for update to authenticated
using (public.is_platform_admin()) with check (public.is_platform_admin());

create policy "Admins can read own notifications" on public.admin_notifications for select to authenticated
using (recipient_user_id = auth.uid() and public.is_platform_admin());
create policy "Admins can update own notifications" on public.admin_notifications for update to authenticated
using (recipient_user_id = auth.uid() and public.is_platform_admin())
with check (recipient_user_id = auth.uid() and public.is_platform_admin());

grant select, insert on public.push_messages to authenticated;
grant update on public.push_messages to authenticated;
grant select, update on public.admin_notifications to authenticated;
grant all on public.push_messages, public.admin_notifications to service_role;
grant usage, select on sequence public.admin_notifications_id_seq to authenticated, service_role;
