-- Trust & safety, support workflow, controlled rollouts and audited merchant support views.
create table if not exists public.abuse_signals (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references public.organizations(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  signal_type text not null,
  severity text not null default 'medium' check (severity in ('low','medium','high','critical')),
  status text not null default 'open' check (status in ('open','investigating','dismissed','confirmed')),
  source_entity_type text,
  source_entity_id text,
  summary text not null,
  evidence jsonb not null default '{}'::jsonb,
  resolved_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);
create unique index if not exists abuse_signals_source_unique on public.abuse_signals(signal_type, source_entity_type, source_entity_id) where source_entity_id is not null;
create index if not exists abuse_signals_queue_idx on public.abuse_signals(status, severity, created_at desc);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade, rating smallint not null check (rating between 1 and 5),
  body text check (char_length(body) <= 2000), verified_visit boolean not null default false,
  status text not null default 'published' check (status in ('published','hidden','removed')),
  moderation_note text, moderated_by uuid references auth.users(id) on delete set null, moderated_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,user_id)
);
create table if not exists public.review_reports (
  id uuid primary key default gen_random_uuid(), review_id uuid not null references public.reviews(id) on delete cascade,
  reporter_user_id uuid references auth.users(id) on delete set null, reason text not null, details text,
  status text not null default 'open' check (status in ('open','dismissed','actioned')),
  resolved_by uuid references auth.users(id) on delete set null, resolved_at timestamptz, created_at timestamptz not null default now()
);
create index if not exists review_reports_queue_idx on public.review_reports(status, created_at);

create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(), ticket_number bigint generated by default as identity unique,
  organization_id uuid references public.organizations(id) on delete set null, requester_user_id uuid references auth.users(id) on delete set null,
  requester_email text, subject text not null, description text not null,
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  status text not null default 'open' check (status in ('open','in_progress','waiting','resolved','closed')),
  assigned_admin_id uuid references auth.users(id) on delete set null, internal_note text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), resolved_at timestamptz
);
create index if not exists support_tickets_queue_idx on public.support_tickets(status, priority, created_at);

create table if not exists public.feature_flags (
  id uuid primary key default gen_random_uuid(), key text not null unique check (key ~ '^[a-z][a-z0-9_.-]{2,79}$'),
  name text not null, description text, enabled boolean not null default false,
  rollout_percentage smallint not null default 0 check (rollout_percentage between 0 and 100),
  organization_ids uuid[] not null default '{}', updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.campaign_plans (
  id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id) on delete cascade,
  name text not null, channel text not null check (channel in ('push','email','in_app','multi')),
  status text not null default 'draft' check (status in ('draft','scheduled','paused','completed','cancelled')),
  audience text not null default 'all_customers', content jsonb not null default '{}'::jsonb,
  scheduled_at timestamptz, owner_admin_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists campaign_plans_schedule_idx on public.campaign_plans(status, scheduled_at);

create table if not exists public.admin_merchant_views (
  id uuid primary key default gen_random_uuid(), admin_user_id uuid not null references auth.users(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade, reason text not null,
  started_at timestamptz not null default now(), expires_at timestamptz not null default (now() + interval '30 minutes'), ended_at timestamptz,
  check (expires_at <= started_at + interval '30 minutes')
);
create index if not exists admin_merchant_views_active_idx on public.admin_merchant_views(admin_user_id, expires_at desc) where ended_at is null;

alter table public.abuse_signals enable row level security; alter table public.reviews enable row level security;
alter table public.review_reports enable row level security; alter table public.support_tickets enable row level security;
alter table public.feature_flags enable row level security; alter table public.campaign_plans enable row level security;
alter table public.admin_merchant_views enable row level security;

create policy "Trust admins manage abuse signals" on public.abuse_signals for all to authenticated using (public.platform_admin_has_permission('trust.view')) with check (public.platform_admin_has_permission('trust.manage'));
create policy "Users read published reviews" on public.reviews for select to authenticated using (status='published' or user_id=auth.uid() or public.platform_admin_has_permission('trust.view'));
create policy "Users create own reviews" on public.reviews for insert to authenticated with check (user_id=auth.uid());
create policy "Trust admins moderate reviews" on public.reviews for update to authenticated using (public.platform_admin_has_permission('trust.manage')) with check (public.platform_admin_has_permission('trust.manage'));
create policy "Authenticated users report reviews" on public.review_reports for insert to authenticated with check (reporter_user_id=auth.uid());
create policy "Trust admins manage reports" on public.review_reports for all to authenticated using (public.platform_admin_has_permission('trust.view')) with check (public.platform_admin_has_permission('trust.manage'));
create policy "Support admins manage tickets" on public.support_tickets for all to authenticated using (public.platform_admin_has_permission('support.view')) with check (public.platform_admin_has_permission('support.manage'));
create policy "Operations admins manage feature flags" on public.feature_flags for all to authenticated using (public.platform_admin_has_permission('feature_flags.manage')) with check (public.platform_admin_has_permission('feature_flags.manage'));
create policy "Operations admins manage campaigns" on public.campaign_plans for all to authenticated using (public.platform_admin_has_permission('campaigns.manage')) with check (public.platform_admin_has_permission('campaigns.manage'));
create policy "Support admins manage merchant views" on public.admin_merchant_views for all to authenticated using (admin_user_id=auth.uid() and public.platform_admin_has_permission('impersonation.manage')) with check (admin_user_id=auth.uid() and public.platform_admin_has_permission('impersonation.manage'));

grant select,insert,update on public.abuse_signals, public.reviews, public.review_reports, public.support_tickets, public.feature_flags, public.campaign_plans, public.admin_merchant_views to authenticated;
grant usage,select on sequence public.support_tickets_ticket_number_seq to authenticated;

create or replace function public.detect_stamp_abuse() returns trigger language plpgsql security definer set search_path=public as $$
declare recent_count integer;
begin
  if new.event_type <> 'award' then return new; end if;
  select count(*) into recent_count from public.stamp_events where user_id=new.user_id and organization_id=new.organization_id and id<>new.id and created_at > now()-interval '10 minutes';
  if recent_count >= 8 then
    insert into public.abuse_signals(organization_id,user_id,signal_type,severity,source_entity_type,source_entity_id,summary,evidence)
    values(new.organization_id,new.user_id,'stamp_velocity',case when recent_count >= 15 then 'critical' else 'high' end,'stamp_event',new.id::text,'Ungewöhnlich viele Stempel in kurzer Zeit',jsonb_build_object('events_in_10_minutes',recent_count+1))
    on conflict do nothing;
  end if;
  return new;
end $$;
drop trigger if exists stamp_events_detect_abuse on public.stamp_events;
create trigger stamp_events_detect_abuse after insert on public.stamp_events for each row execute function public.detect_stamp_abuse();

-- Keep the database permission function aligned with the application matrix.
create or replace function public.platform_admin_has_permission(required_permission text) returns boolean language sql stable security definer set search_path=public as $$
select public.is_platform_admin() and exists(select 1 from public.platform_admins pa where pa.user_id=auth.uid() and pa.is_active=true and (
 pa.role='super_admin' or
 (pa.role='operations' and required_permission=any(array['dashboard.view','organizations.view','organizations.manage','customers.view','customers.manage','marketing.view','marketing.manage','support.view','support.manage','email_templates.view','email_templates.manage','captcha.manage','operations.manage','errors.manage','audit.view','trust.view','trust.manage','feature_flags.manage','campaigns.manage','impersonation.manage'])) or
 (pa.role='support' and required_permission=any(array['dashboard.view','organizations.view','customers.view','customers.manage','marketing.view','support.view','support.manage','trust.view','trust.manage','impersonation.manage'])) or
 (pa.role='finance' and required_permission=any(array['dashboard.view','organizations.view','billing.view','billing.manage','payments.view','payments.manage','audit.view']))
)); $$;
