create table public.stripe_webhook_events (
  id text primary key,
  event_type text not null,
  status text not null default 'processing' check (status in ('processing', 'processed', 'failed')),
  attempts integer not null default 1 check (attempts > 0),
  payload_sha256 text not null,
  error_message text,
  locked_at timestamptz not null default now(),
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.notification_outbox (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references public.organizations(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  recipient_email text not null,
  template text not null check (template in ('team_invitation', 'review_submitted', 'organization_approved', 'organization_rejected', 'privacy_request')),
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'processing', 'sent', 'failed', 'cancelled')),
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz not null default now(),
  last_error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index notification_outbox_pending_idx on public.notification_outbox (next_attempt_at, created_at)
  where status in ('pending', 'failed');

create table public.api_rate_limits (
  bucket text not null,
  key_hash text not null,
  window_start timestamptz not null,
  request_count integer not null default 1 check (request_count > 0),
  primary key (bucket, key_hash, window_start)
);

create table public.sync_tombstones (
  id bigint generated by default as identity primary key,
  resource_type text not null check (resource_type in ('location', 'loyalty_card', 'offer', 'asset')),
  resource_id uuid not null,
  organization_id uuid references public.organizations(id) on delete cascade,
  deleted_at timestamptz not null default now(),
  unique (resource_type, resource_id)
);
create index sync_tombstones_deleted_idx on public.sync_tombstones (deleted_at, id);

create table public.privacy_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  request_type text not null check (request_type in ('export', 'deletion')),
  status text not null default 'requested' check (status in ('requested', 'verified', 'processing', 'completed', 'cancelled', 'rejected')),
  execute_after timestamptz,
  completed_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index privacy_requests_one_open_idx on public.privacy_requests (user_id, request_type)
  where status in ('requested', 'verified', 'processing');

create table public.system_events (
  id bigint generated by default as identity primary key,
  severity text not null check (severity in ('info', 'warning', 'error', 'critical')),
  source text not null,
  message text not null,
  correlation_id text,
  organization_id uuid references public.organizations(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index system_events_severity_created_idx on public.system_events (severity, created_at desc);

create trigger stripe_webhook_events_updated_at before update on public.stripe_webhook_events
for each row execute function public.set_updated_at();
create trigger notification_outbox_updated_at before update on public.notification_outbox
for each row execute function public.set_updated_at();
create trigger privacy_requests_updated_at before update on public.privacy_requests
for each row execute function public.set_updated_at();

create or replace function public.consume_rate_limit(
  rate_bucket text, rate_key_hash text, maximum_requests integer, window_seconds integer
) returns table (allowed boolean, remaining integer, reset_at timestamptz)
language plpgsql security definer set search_path = public as $$
declare
  current_window timestamptz;
  current_count integer;
begin
  if maximum_requests < 1 or window_seconds < 1 or length(rate_bucket) > 80 or length(rate_key_hash) > 128 then
    raise exception 'Invalid rate limit configuration';
  end if;
  current_window := to_timestamp(floor(extract(epoch from now()) / window_seconds) * window_seconds);
  insert into public.api_rate_limits (bucket, key_hash, window_start, request_count)
  values (rate_bucket, rate_key_hash, current_window, 1)
  on conflict (bucket, key_hash, window_start)
  do update set request_count = public.api_rate_limits.request_count + 1
  returning request_count into current_count;
  return query select current_count <= maximum_requests,
    greatest(maximum_requests - current_count, 0), current_window + make_interval(secs => window_seconds);
end;
$$;

create or replace function public.claim_notifications(batch_size integer default 25)
returns setof public.notification_outbox
language plpgsql security definer set search_path = public as $$
begin
  return query
  with selected as (
    select id from public.notification_outbox
    where (
      (status in ('pending', 'failed') and next_attempt_at <= now())
      or (status = 'processing' and updated_at < now() - interval '10 minutes')
    ) and attempts < 8
    order by created_at for update skip locked limit least(greatest(batch_size, 1), 100)
  ), updated as (
    update public.notification_outbox n set status = 'processing', attempts = attempts + 1
    from selected where n.id = selected.id returning n.*
  ) select * from updated;
end;
$$;

create or replace function public.cleanup_operational_data()
returns jsonb language plpgsql security definer set search_path = public as $$
declare rate_limits_deleted integer; notifications_deleted integer; webhooks_deleted integer; tombstones_deleted integer; events_deleted integer;
begin
  delete from public.api_rate_limits where window_start < now() - interval '2 days'; get diagnostics rate_limits_deleted = row_count;
  delete from public.notification_outbox where status in ('sent', 'cancelled') and updated_at < now() - interval '90 days'; get diagnostics notifications_deleted = row_count;
  delete from public.stripe_webhook_events where status = 'processed' and processed_at < now() - interval '180 days'; get diagnostics webhooks_deleted = row_count;
  delete from public.sync_tombstones where deleted_at < now() - interval '365 days'; get diagnostics tombstones_deleted = row_count;
  delete from public.system_events where (severity = 'info' and created_at < now() - interval '90 days') or (severity <> 'info' and created_at < now() - interval '365 days'); get diagnostics events_deleted = row_count;
  return jsonb_build_object('rate_limits', rate_limits_deleted, 'notifications', notifications_deleted, 'webhooks', webhooks_deleted, 'tombstones', tombstones_deleted, 'system_events', events_deleted);
end;
$$;

create or replace function public.record_sync_tombstone()
returns trigger language plpgsql security definer set search_path = public as $$
declare kind text;
begin
  kind := case tg_table_name
    when 'locations' then 'location'
    when 'loyalty_cards' then 'loyalty_card'
    when 'offers' then 'offer'
    when 'organization_assets' then 'asset'
  end;
  insert into public.sync_tombstones (resource_type, resource_id, organization_id)
  values (kind, old.id, old.organization_id)
  on conflict (resource_type, resource_id) do update set deleted_at = now(), organization_id = excluded.organization_id;
  return old;
end;
$$;

create trigger locations_sync_tombstone after delete on public.locations
for each row execute function public.record_sync_tombstone();
create trigger loyalty_cards_sync_tombstone after delete on public.loyalty_cards
for each row execute function public.record_sync_tombstone();
create trigger offers_sync_tombstone after delete on public.offers
for each row execute function public.record_sync_tombstone();
create trigger organization_assets_sync_tombstone after delete on public.organization_assets
for each row execute function public.record_sync_tombstone();

alter table public.stripe_webhook_events enable row level security;
alter table public.notification_outbox enable row level security;
alter table public.api_rate_limits enable row level security;
alter table public.sync_tombstones enable row level security;
alter table public.privacy_requests enable row level security;
alter table public.system_events enable row level security;

create policy "Users can read own privacy requests" on public.privacy_requests for select to authenticated
  using (user_id = auth.uid() or public.is_platform_admin());
create policy "Users can create own privacy requests" on public.privacy_requests for insert to authenticated
  with check (user_id = auth.uid());
create policy "Users can cancel own privacy requests" on public.privacy_requests for update to authenticated
  using (user_id = auth.uid() and status = 'requested')
  with check (user_id = auth.uid() and status = 'cancelled');
create policy "Platform admins can manage privacy requests" on public.privacy_requests for all to authenticated
  using (public.is_platform_admin()) with check (public.is_platform_admin());
create policy "Platform admins can read system events" on public.system_events for select to authenticated
  using (public.is_platform_admin());
create policy "Platform admins can read Stripe webhook events" on public.stripe_webhook_events for select to authenticated
  using (public.is_platform_admin());
create policy "Platform admins can manage notification outbox" on public.notification_outbox for all to authenticated
  using (public.is_platform_admin()) with check (public.is_platform_admin());
create policy "Public can read sync tombstones" on public.sync_tombstones for select to anon, authenticated using (true);

revoke all on function public.consume_rate_limit(text, text, integer, integer) from public, anon, authenticated;
revoke all on function public.claim_notifications(integer) from public, anon, authenticated;
revoke all on function public.cleanup_operational_data() from public, anon, authenticated;
grant execute on function public.consume_rate_limit(text, text, integer, integer) to service_role;
grant execute on function public.claim_notifications(integer) to service_role;
grant execute on function public.cleanup_operational_data() to service_role;
grant select, insert, update on public.privacy_requests to authenticated;
grant select on public.sync_tombstones to anon, authenticated;
grant select on public.stripe_webhook_events, public.system_events to authenticated;
grant select, update on public.notification_outbox to authenticated;
grant all on public.stripe_webhook_events, public.notification_outbox, public.api_rate_limits, public.sync_tombstones, public.privacy_requests, public.system_events to service_role;
grant usage, select on all sequences in schema public to service_role;
