import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminDecisionButton } from "@/components/AdminDecisionButton";
import { requirePlatformAdmin } from "@/lib/admin";
import { setCustomerApproval } from "../actions";

type Params = Promise<{ id: string }>;
type SearchParams = Promise<{ saved?: string; error?: string }>;

export default async function CustomerDetailPage({ params, searchParams }: { params: Params; searchParams: SearchParams }) {
  const [{ id }, query, { supabase }] = await Promise.all([params, searchParams, requirePlatformAdmin("customers.view")]);
  const [{ data: customer }, { data: profile }, { data: cards }, { data: events }, { data: rewards }, { data: acceptances }] = await Promise.all([
    supabase.from("customer_profiles").select("*").eq("user_id", id).maybeSingle(),
    supabase.from("profiles").select("id,email,full_name,account_type,created_at,updated_at").eq("id", id).maybeSingle(),
    supabase.from("customer_loyalty_cards").select("id,stamps_balance,lifetime_stamps,created_at,updated_at,loyalty_cards(title,organizations(name))").eq("user_id", id).order("updated_at", { ascending: false }),
    supabase.from("stamp_events").select("id,event_type,amount,created_at,organizations(name),locations(name)").eq("user_id", id).order("created_at", { ascending: false }).limit(50),
    supabase.from("reward_entitlements").select("id,reward_title,status,created_at,expires_at,organizations(name)").eq("user_id", id).order("created_at", { ascending: false }).limit(50),
    supabase.from("legal_acceptances").select("document_type,document_version,accepted_at").eq("user_id", id).order("accepted_at", { ascending: false }),
  ]);
  if (!customer || !profile || profile.account_type === "business") notFound();
  return <main className="min-h-screen bg-slate-950 px-5 py-14 text-white sm:px-8"><section className="mx-auto max-w-6xl">
    <Link href="/admin/customers" className="font-black text-purple-200">← Zur Kundenliste</Link>
    <div className="mt-7 flex flex-wrap items-start justify-between gap-5"><div><p className="font-mono text-cyan-200">{customer.customer_number}</p><h1 className="mt-2 text-4xl font-black">{customer.display_name || profile.full_name || "Kunde ohne Namen"}</h1><p className="mt-2 text-slate-300">{profile.email}</p></div><Status value={customer.approval_status}/></div>
    {query.saved?<p className="mt-6 rounded-2xl bg-emerald-300/10 p-4 text-emerald-100">Kundenstatus wurde gespeichert.</p>:null}{query.error?<p className="mt-6 rounded-2xl bg-red-300/10 p-4 text-red-100">Aktion fehlgeschlagen ({query.error}).</p>:null}
    <div className="mt-8 grid gap-4 md:grid-cols-4"><Metric label="Treuekarten" value={cards?.length??0}/><Metric label="Stempel gesamt" value={(cards??[]).reduce((sum,c)=>sum+c.lifetime_stamps,0)}/><Metric label="Belohnungen" value={rewards?.length??0}/><Metric label="Registriert" value={new Date(customer.created_at).toLocaleDateString("de-AT")}/></div>
    <section className="mt-8 rounded-3xl border border-white/10 bg-white/[0.05] p-6"><h2 className="text-2xl font-black">Prüfung und Freigabe</h2><p className="mt-3 text-sm text-slate-400">E-Mail: {profile.email} · Marketing-Einwilligung: {customer.marketing_consent?"Ja":"Nein"}</p>{customer.rejection_reason?<p className="mt-3 rounded-xl bg-red-300/10 p-3 text-red-100">Grund: {customer.rejection_reason}</p>:null}<div className="mt-5 flex flex-wrap gap-3">{customer.approval_status!=="approved"?<Decision id={id} decision="approve" label="Kunde freigeben"/>:null}{customer.approval_status==="approved"?<Decision id={id} decision="suspend" label="Kunde sperren" tone="danger"/>:null}</div>{customer.approval_status!=="approved"?<form action={setCustomerApproval} className="mt-5 grid max-w-2xl gap-3"><input type="hidden" name="customer_id" value={id}/><input type="hidden" name="decision" value="reject"/><input type="hidden" name="return_to" value={`/admin/customers/${id}`}/><label className="grid gap-2 text-sm font-bold">Ablehnungsgrund<textarea name="reason" required minLength={3} maxLength={500} className="min-h-24 rounded-xl bg-slate-900 p-4"/></label><AdminDecisionButton label="Registrierung ablehnen" tone="danger" confirmation="Diese Registrierung wirklich ablehnen? Der Kunde erhält keinen Zugriff."/></form>:null}</section>
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><List title="Treuekarten">{(cards??[]).map(card=>{const loyalty=first(card.loyalty_cards);const organization=first(loyalty?.organizations);return <Row key={card.id} title={`${organization?.name??"Geschäft"} · ${loyalty?.title??"Treuekarte"}`} text={`${card.stamps_balance} aktuell · ${card.lifetime_stamps} insgesamt`}/>})}</List><List title="Rechtliche Einwilligungen">{(acceptances??[]).map((item,index)=><Row key={`${item.document_type}-${index}`} title={`${item.document_type} · ${item.document_version}`} text={new Date(item.accepted_at).toLocaleString("de-AT")}/>)}</List><List title="Letzte Stempel">{(events??[]).map(event=>{const organization=first(event.organizations);const location=first(event.locations);return <Row key={event.id} title={`${organization?.name??"Geschäft"} · ${location?.name??"Filiale"}`} text={`${event.amount} · ${new Date(event.created_at).toLocaleString("de-AT")}`}/>})}</List><List title="Belohnungen">{(rewards??[]).map(reward=>{const organization=first(reward.organizations);return <Row key={reward.id} title={`${reward.reward_title} · ${organization?.name??"Geschäft"}`} text={`${reward.status} · ${new Date(reward.created_at).toLocaleString("de-AT")}`}/>})}</List></div>
  </section></main>;
}
function Decision({id,decision,label,tone="default"}:{id:string;decision:string;label:string;tone?:"default"|"danger"|"warning"}){return <form action={setCustomerApproval}><input type="hidden" name="customer_id" value={id}/><input type="hidden" name="decision" value={decision}/><input type="hidden" name="return_to" value={`/admin/customers/${id}`}/><AdminDecisionButton label={label} tone={tone} confirmation={decision==="suspend"?"Dieses Kundenkonto wirklich sperren? Wallet und Stempelfunktion werden deaktiviert.":undefined}/></form>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-3xl border border-white/10 bg-white/[0.05] p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>}
function Status({value}:{value:string}){const style=value==="approved"?"bg-emerald-300/15 text-emerald-100":value==="pending"?"bg-amber-300/15 text-amber-100":"bg-red-300/15 text-red-100";return <span className={`rounded-full px-4 py-2 text-sm font-black ${style}`}>{value==="approved"?"Freigegeben":value==="pending"?"In Prüfung":value==="rejected"?"Abgelehnt":"Gesperrt"}</span>}
function List({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-3xl border border-white/10 bg-white/[0.05] p-6"><h2 className="text-2xl font-black">{title}</h2><div className="mt-4 grid gap-3">{children||<p className="text-slate-500">Keine Daten.</p>}</div></section>}
function Row({title,text}:{title:string;text:string}){return <div className="rounded-xl bg-white/[0.04] p-4"><p className="font-bold">{title}</p><p className="mt-1 text-sm text-slate-400">{text}</p></div>}
function first<T>(value:T|T[]|null|undefined):T|undefined{return Array.isArray(value)?value[0]:value??undefined}
